version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    # 额外启用的 linters
    - bodyclose      # 检查 HTTP response body 是否关闭
    - dogsled        # 检查过多的空白标识符赋值
    - dupl           # 检查重复代码
    - goconst        # 检查可以替换为常量的字符串
    - gocritic       # 提供代码诊断
    - gosec          # 安全检查
    - misspell       # 检查拼写错误
    - nakedret       # 检查裸返回
    - noctx          # 检查 HTTP 请求是否带 context
    - prealloc       # 检查 slice 预分配
    - unconvert      # 检查不必要的类型转换
    - unparam        # 检查未使用的参数
    - whitespace     # 检查不必要的空白行

  disable:
    - funlen         # 函数长度检查（暂时禁用，后续重构后启用）
    - gocyclo        # 圈复杂度检查（暂时禁用）
    - lll            # 行长度检查
    - wsl            # 空白行风格

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    paths:
      - ent
      - docs
      - third_party
      - ".*_test\\.go"
    rules:
      # 控制器和服务中的 CRUD 操作具有相似结构，排除 dupl 检查
      - path: internal/controller/
        linters:
          - dupl
      - path: internal/service/
        linters:
          - dupl

settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write

  govet:
    check-shadowing: true
    disable:
      - fieldalignment # 字段对齐检查（会产生大量警告）

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - hugeParam      # 大参数检查（struct 较大时会产生警告）
      - rangeValCopy   # range 值拷贝检查

  gosec:
    excludes:
      - G104 # 忽略未检查的错误（已有 errcheck）
      - G304 # 文件路径由变量指定（在某些场景下是合理的）

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  dupl:
    threshold: 150

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

issues:
  max-issues-per-linter: 50
  max-same-issues: 10

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/PokeForum/PokeForum

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true
