run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - ent
    - docs

linters:
  enable:
    # 默认启用的 linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # 额外启用的 linters
    - bodyclose      # 检查 HTTP response body 是否关闭
    - dogsled        # 检查过多的空白标识符赋值
    - dupl           # 检查重复代码
    - exportloopref  # 检查循环变量指针导出
    - gochecknoinits # 检查 init 函数使用
    - goconst        # 检查可以替换为常量的字符串
    - gocritic       # 提供代码诊断
    - gofmt          # 检查代码格式
    - goimports      # 检查 import 语句
    - goprintffuncname # 检查 printf 函数命名
    - gosec          # 安全检查
    - misspell       # 检查拼写错误
    - nakedret       # 检查裸返回
    - noctx          # 检查 HTTP 请求是否带 context
    - prealloc       # 检查 slice 预分配
    - rowserrcheck   # 检查 sql.Rows.Err 是否被检查
    - sqlclosecheck  # 检查 sql.Rows 是否关闭
    - unconvert      # 检查不必要的类型转换
    - unparam        # 检查未使用的参数
    - whitespace     # 检查不必要的空白行

  disable:
    - funlen         # 函数长度检查（暂时禁用，后续重构后启用）
    - gocyclo        # 圈复杂度检查（暂时禁用）
    - lll            # 行长度检查
    - wsl            # 空白行风格

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write

  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment # 字段对齐检查（会产生大量警告）

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/PokeForum/PokeForum

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - hugeParam      # 大参数检查（struct 较大时会产生警告）
      - rangeValCopy   # range 值拷贝检查

  gosec:
    excludes:
      - G104 # 忽略未检查的错误（已有 errcheck）
      - G304 # 文件路径由变量指定（在某些场景下是合理的）

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  dupl:
    threshold: 150

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

issues:
  exclude-rules:
    # 测试文件中允许的规则
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst

    # ent 生成的代码排除检查
    - path: ent/
      linters:
        - all

    # docs 生成的代码排除检查
    - path: docs/
      linters:
        - all

    # main.go 允许使用 init
    - path: main\.go
      linters:
        - gochecknoinits

  max-issues-per-linter: 50
  max-same-issues: 10
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
