// Code generated by ent, DO NOT EDIT.

package oauthprovider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/PokeForum/PokeForum/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldClientID, v))
}

// ClientSecret applies equality check predicate on the "client_secret" field. It's identical to ClientSecretEQ.
func ClientSecret(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldClientSecret, v))
}

// AuthURL applies equality check predicate on the "auth_url" field. It's identical to AuthURLEQ.
func AuthURL(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldAuthURL, v))
}

// TokenURL applies equality check predicate on the "token_url" field. It's identical to TokenURLEQ.
func TokenURL(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldTokenURL, v))
}

// UserInfoURL applies equality check predicate on the "user_info_url" field. It's identical to UserInfoURLEQ.
func UserInfoURL(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldUserInfoURL, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldEnabled, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v Provider) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v Provider) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...Provider) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...Provider) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotIn(FieldProvider, vs...))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDIsNil applies the IsNil predicate on the "client_id" field.
func ClientIDIsNil() predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIsNull(FieldClientID))
}

// ClientIDNotNil applies the NotNil predicate on the "client_id" field.
func ClientIDNotNil() predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotNull(FieldClientID))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldContainsFold(FieldClientID, v))
}

// ClientSecretEQ applies the EQ predicate on the "client_secret" field.
func ClientSecretEQ(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldClientSecret, v))
}

// ClientSecretNEQ applies the NEQ predicate on the "client_secret" field.
func ClientSecretNEQ(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNEQ(FieldClientSecret, v))
}

// ClientSecretIn applies the In predicate on the "client_secret" field.
func ClientSecretIn(vs ...string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIn(FieldClientSecret, vs...))
}

// ClientSecretNotIn applies the NotIn predicate on the "client_secret" field.
func ClientSecretNotIn(vs ...string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotIn(FieldClientSecret, vs...))
}

// ClientSecretGT applies the GT predicate on the "client_secret" field.
func ClientSecretGT(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGT(FieldClientSecret, v))
}

// ClientSecretGTE applies the GTE predicate on the "client_secret" field.
func ClientSecretGTE(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGTE(FieldClientSecret, v))
}

// ClientSecretLT applies the LT predicate on the "client_secret" field.
func ClientSecretLT(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLT(FieldClientSecret, v))
}

// ClientSecretLTE applies the LTE predicate on the "client_secret" field.
func ClientSecretLTE(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLTE(FieldClientSecret, v))
}

// ClientSecretContains applies the Contains predicate on the "client_secret" field.
func ClientSecretContains(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldContains(FieldClientSecret, v))
}

// ClientSecretHasPrefix applies the HasPrefix predicate on the "client_secret" field.
func ClientSecretHasPrefix(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldHasPrefix(FieldClientSecret, v))
}

// ClientSecretHasSuffix applies the HasSuffix predicate on the "client_secret" field.
func ClientSecretHasSuffix(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldHasSuffix(FieldClientSecret, v))
}

// ClientSecretIsNil applies the IsNil predicate on the "client_secret" field.
func ClientSecretIsNil() predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIsNull(FieldClientSecret))
}

// ClientSecretNotNil applies the NotNil predicate on the "client_secret" field.
func ClientSecretNotNil() predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotNull(FieldClientSecret))
}

// ClientSecretEqualFold applies the EqualFold predicate on the "client_secret" field.
func ClientSecretEqualFold(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEqualFold(FieldClientSecret, v))
}

// ClientSecretContainsFold applies the ContainsFold predicate on the "client_secret" field.
func ClientSecretContainsFold(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldContainsFold(FieldClientSecret, v))
}

// AuthURLEQ applies the EQ predicate on the "auth_url" field.
func AuthURLEQ(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldAuthURL, v))
}

// AuthURLNEQ applies the NEQ predicate on the "auth_url" field.
func AuthURLNEQ(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNEQ(FieldAuthURL, v))
}

// AuthURLIn applies the In predicate on the "auth_url" field.
func AuthURLIn(vs ...string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIn(FieldAuthURL, vs...))
}

// AuthURLNotIn applies the NotIn predicate on the "auth_url" field.
func AuthURLNotIn(vs ...string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotIn(FieldAuthURL, vs...))
}

// AuthURLGT applies the GT predicate on the "auth_url" field.
func AuthURLGT(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGT(FieldAuthURL, v))
}

// AuthURLGTE applies the GTE predicate on the "auth_url" field.
func AuthURLGTE(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGTE(FieldAuthURL, v))
}

// AuthURLLT applies the LT predicate on the "auth_url" field.
func AuthURLLT(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLT(FieldAuthURL, v))
}

// AuthURLLTE applies the LTE predicate on the "auth_url" field.
func AuthURLLTE(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLTE(FieldAuthURL, v))
}

// AuthURLContains applies the Contains predicate on the "auth_url" field.
func AuthURLContains(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldContains(FieldAuthURL, v))
}

// AuthURLHasPrefix applies the HasPrefix predicate on the "auth_url" field.
func AuthURLHasPrefix(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldHasPrefix(FieldAuthURL, v))
}

// AuthURLHasSuffix applies the HasSuffix predicate on the "auth_url" field.
func AuthURLHasSuffix(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldHasSuffix(FieldAuthURL, v))
}

// AuthURLIsNil applies the IsNil predicate on the "auth_url" field.
func AuthURLIsNil() predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIsNull(FieldAuthURL))
}

// AuthURLNotNil applies the NotNil predicate on the "auth_url" field.
func AuthURLNotNil() predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotNull(FieldAuthURL))
}

// AuthURLEqualFold applies the EqualFold predicate on the "auth_url" field.
func AuthURLEqualFold(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEqualFold(FieldAuthURL, v))
}

// AuthURLContainsFold applies the ContainsFold predicate on the "auth_url" field.
func AuthURLContainsFold(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldContainsFold(FieldAuthURL, v))
}

// TokenURLEQ applies the EQ predicate on the "token_url" field.
func TokenURLEQ(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldTokenURL, v))
}

// TokenURLNEQ applies the NEQ predicate on the "token_url" field.
func TokenURLNEQ(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNEQ(FieldTokenURL, v))
}

// TokenURLIn applies the In predicate on the "token_url" field.
func TokenURLIn(vs ...string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIn(FieldTokenURL, vs...))
}

// TokenURLNotIn applies the NotIn predicate on the "token_url" field.
func TokenURLNotIn(vs ...string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotIn(FieldTokenURL, vs...))
}

// TokenURLGT applies the GT predicate on the "token_url" field.
func TokenURLGT(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGT(FieldTokenURL, v))
}

// TokenURLGTE applies the GTE predicate on the "token_url" field.
func TokenURLGTE(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGTE(FieldTokenURL, v))
}

// TokenURLLT applies the LT predicate on the "token_url" field.
func TokenURLLT(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLT(FieldTokenURL, v))
}

// TokenURLLTE applies the LTE predicate on the "token_url" field.
func TokenURLLTE(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLTE(FieldTokenURL, v))
}

// TokenURLContains applies the Contains predicate on the "token_url" field.
func TokenURLContains(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldContains(FieldTokenURL, v))
}

// TokenURLHasPrefix applies the HasPrefix predicate on the "token_url" field.
func TokenURLHasPrefix(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldHasPrefix(FieldTokenURL, v))
}

// TokenURLHasSuffix applies the HasSuffix predicate on the "token_url" field.
func TokenURLHasSuffix(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldHasSuffix(FieldTokenURL, v))
}

// TokenURLIsNil applies the IsNil predicate on the "token_url" field.
func TokenURLIsNil() predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIsNull(FieldTokenURL))
}

// TokenURLNotNil applies the NotNil predicate on the "token_url" field.
func TokenURLNotNil() predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotNull(FieldTokenURL))
}

// TokenURLEqualFold applies the EqualFold predicate on the "token_url" field.
func TokenURLEqualFold(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEqualFold(FieldTokenURL, v))
}

// TokenURLContainsFold applies the ContainsFold predicate on the "token_url" field.
func TokenURLContainsFold(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldContainsFold(FieldTokenURL, v))
}

// UserInfoURLEQ applies the EQ predicate on the "user_info_url" field.
func UserInfoURLEQ(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldUserInfoURL, v))
}

// UserInfoURLNEQ applies the NEQ predicate on the "user_info_url" field.
func UserInfoURLNEQ(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNEQ(FieldUserInfoURL, v))
}

// UserInfoURLIn applies the In predicate on the "user_info_url" field.
func UserInfoURLIn(vs ...string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIn(FieldUserInfoURL, vs...))
}

// UserInfoURLNotIn applies the NotIn predicate on the "user_info_url" field.
func UserInfoURLNotIn(vs ...string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotIn(FieldUserInfoURL, vs...))
}

// UserInfoURLGT applies the GT predicate on the "user_info_url" field.
func UserInfoURLGT(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGT(FieldUserInfoURL, v))
}

// UserInfoURLGTE applies the GTE predicate on the "user_info_url" field.
func UserInfoURLGTE(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGTE(FieldUserInfoURL, v))
}

// UserInfoURLLT applies the LT predicate on the "user_info_url" field.
func UserInfoURLLT(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLT(FieldUserInfoURL, v))
}

// UserInfoURLLTE applies the LTE predicate on the "user_info_url" field.
func UserInfoURLLTE(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLTE(FieldUserInfoURL, v))
}

// UserInfoURLContains applies the Contains predicate on the "user_info_url" field.
func UserInfoURLContains(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldContains(FieldUserInfoURL, v))
}

// UserInfoURLHasPrefix applies the HasPrefix predicate on the "user_info_url" field.
func UserInfoURLHasPrefix(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldHasPrefix(FieldUserInfoURL, v))
}

// UserInfoURLHasSuffix applies the HasSuffix predicate on the "user_info_url" field.
func UserInfoURLHasSuffix(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldHasSuffix(FieldUserInfoURL, v))
}

// UserInfoURLIsNil applies the IsNil predicate on the "user_info_url" field.
func UserInfoURLIsNil() predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIsNull(FieldUserInfoURL))
}

// UserInfoURLNotNil applies the NotNil predicate on the "user_info_url" field.
func UserInfoURLNotNil() predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotNull(FieldUserInfoURL))
}

// UserInfoURLEqualFold applies the EqualFold predicate on the "user_info_url" field.
func UserInfoURLEqualFold(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEqualFold(FieldUserInfoURL, v))
}

// UserInfoURLContainsFold applies the ContainsFold predicate on the "user_info_url" field.
func UserInfoURLContainsFold(v string) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldContainsFold(FieldUserInfoURL, v))
}

// ScopesIsNil applies the IsNil predicate on the "scopes" field.
func ScopesIsNil() predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIsNull(FieldScopes))
}

// ScopesNotNil applies the NotNil predicate on the "scopes" field.
func ScopesNotNil() predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotNull(FieldScopes))
}

// ExtraConfigIsNil applies the IsNil predicate on the "extra_config" field.
func ExtraConfigIsNil() predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIsNull(FieldExtraConfig))
}

// ExtraConfigNotNil applies the NotNil predicate on the "extra_config" field.
func ExtraConfigNotNil() predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotNull(FieldExtraConfig))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNEQ(FieldEnabled, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.FieldLTE(FieldSortOrder, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthProvider) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthProvider) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthProvider) predicate.OAuthProvider {
	return predicate.OAuthProvider(sql.NotPredicates(p))
}
