// Code generated by ent, DO NOT EDIT.

package usersigninstatus

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usersigninstatus type in the database.
	Label = "user_signin_status"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldLastSigninDate holds the string denoting the last_signin_date field in the database.
	FieldLastSigninDate = "last_signin_date"
	// FieldContinuousDays holds the string denoting the continuous_days field in the database.
	FieldContinuousDays = "continuous_days"
	// FieldTotalDays holds the string denoting the total_days field in the database.
	FieldTotalDays = "total_days"
	// Table holds the table name of the usersigninstatus in the database.
	Table = "user_signin_status"
)

// Columns holds all SQL columns for usersigninstatus fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldLastSigninDate,
	FieldContinuousDays,
	FieldTotalDays,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(int64) error
	// DefaultContinuousDays holds the default value on creation for the "continuous_days" field.
	DefaultContinuousDays int
	// ContinuousDaysValidator is a validator for the "continuous_days" field. It is called by the builders before save.
	ContinuousDaysValidator func(int) error
	// DefaultTotalDays holds the default value on creation for the "total_days" field.
	DefaultTotalDays int
	// TotalDaysValidator is a validator for the "total_days" field. It is called by the builders before save.
	TotalDaysValidator func(int) error
)

// OrderOption defines the ordering options for the UserSigninStatus queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByLastSigninDate orders the results by the last_signin_date field.
func ByLastSigninDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSigninDate, opts...).ToFunc()
}

// ByContinuousDays orders the results by the continuous_days field.
func ByContinuousDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContinuousDays, opts...).ToFunc()
}

// ByTotalDays orders the results by the total_days field.
func ByTotalDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalDays, opts...).ToFunc()
}
