// Code generated by ent, DO NOT EDIT.

package usersigninstatus

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/PokeForum/PokeForum/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldEQ(FieldUserID, v))
}

// LastSigninDate applies equality check predicate on the "last_signin_date" field. It's identical to LastSigninDateEQ.
func LastSigninDate(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldEQ(FieldLastSigninDate, v))
}

// ContinuousDays applies equality check predicate on the "continuous_days" field. It's identical to ContinuousDaysEQ.
func ContinuousDays(v int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldEQ(FieldContinuousDays, v))
}

// TotalDays applies equality check predicate on the "total_days" field. It's identical to TotalDaysEQ.
func TotalDays(v int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldEQ(FieldTotalDays, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldLTE(FieldUserID, v))
}

// LastSigninDateEQ applies the EQ predicate on the "last_signin_date" field.
func LastSigninDateEQ(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldEQ(FieldLastSigninDate, v))
}

// LastSigninDateNEQ applies the NEQ predicate on the "last_signin_date" field.
func LastSigninDateNEQ(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldNEQ(FieldLastSigninDate, v))
}

// LastSigninDateIn applies the In predicate on the "last_signin_date" field.
func LastSigninDateIn(vs ...time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldIn(FieldLastSigninDate, vs...))
}

// LastSigninDateNotIn applies the NotIn predicate on the "last_signin_date" field.
func LastSigninDateNotIn(vs ...time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldNotIn(FieldLastSigninDate, vs...))
}

// LastSigninDateGT applies the GT predicate on the "last_signin_date" field.
func LastSigninDateGT(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldGT(FieldLastSigninDate, v))
}

// LastSigninDateGTE applies the GTE predicate on the "last_signin_date" field.
func LastSigninDateGTE(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldGTE(FieldLastSigninDate, v))
}

// LastSigninDateLT applies the LT predicate on the "last_signin_date" field.
func LastSigninDateLT(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldLT(FieldLastSigninDate, v))
}

// LastSigninDateLTE applies the LTE predicate on the "last_signin_date" field.
func LastSigninDateLTE(v time.Time) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldLTE(FieldLastSigninDate, v))
}

// ContinuousDaysEQ applies the EQ predicate on the "continuous_days" field.
func ContinuousDaysEQ(v int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldEQ(FieldContinuousDays, v))
}

// ContinuousDaysNEQ applies the NEQ predicate on the "continuous_days" field.
func ContinuousDaysNEQ(v int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldNEQ(FieldContinuousDays, v))
}

// ContinuousDaysIn applies the In predicate on the "continuous_days" field.
func ContinuousDaysIn(vs ...int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldIn(FieldContinuousDays, vs...))
}

// ContinuousDaysNotIn applies the NotIn predicate on the "continuous_days" field.
func ContinuousDaysNotIn(vs ...int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldNotIn(FieldContinuousDays, vs...))
}

// ContinuousDaysGT applies the GT predicate on the "continuous_days" field.
func ContinuousDaysGT(v int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldGT(FieldContinuousDays, v))
}

// ContinuousDaysGTE applies the GTE predicate on the "continuous_days" field.
func ContinuousDaysGTE(v int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldGTE(FieldContinuousDays, v))
}

// ContinuousDaysLT applies the LT predicate on the "continuous_days" field.
func ContinuousDaysLT(v int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldLT(FieldContinuousDays, v))
}

// ContinuousDaysLTE applies the LTE predicate on the "continuous_days" field.
func ContinuousDaysLTE(v int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldLTE(FieldContinuousDays, v))
}

// TotalDaysEQ applies the EQ predicate on the "total_days" field.
func TotalDaysEQ(v int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldEQ(FieldTotalDays, v))
}

// TotalDaysNEQ applies the NEQ predicate on the "total_days" field.
func TotalDaysNEQ(v int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldNEQ(FieldTotalDays, v))
}

// TotalDaysIn applies the In predicate on the "total_days" field.
func TotalDaysIn(vs ...int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldIn(FieldTotalDays, vs...))
}

// TotalDaysNotIn applies the NotIn predicate on the "total_days" field.
func TotalDaysNotIn(vs ...int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldNotIn(FieldTotalDays, vs...))
}

// TotalDaysGT applies the GT predicate on the "total_days" field.
func TotalDaysGT(v int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldGT(FieldTotalDays, v))
}

// TotalDaysGTE applies the GTE predicate on the "total_days" field.
func TotalDaysGTE(v int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldGTE(FieldTotalDays, v))
}

// TotalDaysLT applies the LT predicate on the "total_days" field.
func TotalDaysLT(v int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldLT(FieldTotalDays, v))
}

// TotalDaysLTE applies the LTE predicate on the "total_days" field.
func TotalDaysLTE(v int) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.FieldLTE(FieldTotalDays, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserSigninStatus) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserSigninStatus) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserSigninStatus) predicate.UserSigninStatus {
	return predicate.UserSigninStatus(sql.NotPredicates(p))
}
