// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PokeForum/PokeForum/ent/categorymoderator"
	"github.com/PokeForum/PokeForum/ent/predicate"
)

// CategoryModeratorDelete is the builder for deleting a CategoryModerator entity.
type CategoryModeratorDelete struct {
	config
	hooks    []Hook
	mutation *CategoryModeratorMutation
}

// Where appends a list predicates to the CategoryModeratorDelete builder.
func (_d *CategoryModeratorDelete) Where(ps ...predicate.CategoryModerator) *CategoryModeratorDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CategoryModeratorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CategoryModeratorDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CategoryModeratorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(categorymoderator.Table, sqlgraph.NewFieldSpec(categorymoderator.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CategoryModeratorDeleteOne is the builder for deleting a single CategoryModerator entity.
type CategoryModeratorDeleteOne struct {
	_d *CategoryModeratorDelete
}

// Where appends a list predicates to the CategoryModeratorDelete builder.
func (_d *CategoryModeratorDeleteOne) Where(ps ...predicate.CategoryModerator) *CategoryModeratorDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CategoryModeratorDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{categorymoderator.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CategoryModeratorDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
