// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PokeForum/PokeForum/ent/comment"
	"github.com/PokeForum/PokeForum/ent/predicate"
)

// CommentUpdate is the builder for updating Comment entities.
type CommentUpdate struct {
	config
	hooks    []Hook
	mutation *CommentMutation
}

// Where appends a list predicates to the CommentUpdate builder.
func (_u *CommentUpdate) Where(ps ...predicate.Comment) *CommentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommentUpdate) SetUpdatedAt(v time.Time) *CommentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPostID sets the "post_id" field.
func (_u *CommentUpdate) SetPostID(v int) *CommentUpdate {
	_u.mutation.ResetPostID()
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *CommentUpdate) SetNillablePostID(v *int) *CommentUpdate {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// AddPostID adds value to the "post_id" field.
func (_u *CommentUpdate) AddPostID(v int) *CommentUpdate {
	_u.mutation.AddPostID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CommentUpdate) SetUserID(v int) *CommentUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableUserID(v *int) *CommentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CommentUpdate) AddUserID(v int) *CommentUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *CommentUpdate) SetParentID(v int) *CommentUpdate {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableParentID(v *int) *CommentUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *CommentUpdate) AddParentID(v int) *CommentUpdate {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *CommentUpdate) ClearParentID() *CommentUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetReplyToUserID sets the "reply_to_user_id" field.
func (_u *CommentUpdate) SetReplyToUserID(v int) *CommentUpdate {
	_u.mutation.ResetReplyToUserID()
	_u.mutation.SetReplyToUserID(v)
	return _u
}

// SetNillableReplyToUserID sets the "reply_to_user_id" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableReplyToUserID(v *int) *CommentUpdate {
	if v != nil {
		_u.SetReplyToUserID(*v)
	}
	return _u
}

// AddReplyToUserID adds value to the "reply_to_user_id" field.
func (_u *CommentUpdate) AddReplyToUserID(v int) *CommentUpdate {
	_u.mutation.AddReplyToUserID(v)
	return _u
}

// ClearReplyToUserID clears the value of the "reply_to_user_id" field.
func (_u *CommentUpdate) ClearReplyToUserID() *CommentUpdate {
	_u.mutation.ClearReplyToUserID()
	return _u
}

// SetContent sets the "content" field.
func (_u *CommentUpdate) SetContent(v string) *CommentUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableContent(v *string) *CommentUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *CommentUpdate) SetLikeCount(v int) *CommentUpdate {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableLikeCount(v *int) *CommentUpdate {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *CommentUpdate) AddLikeCount(v int) *CommentUpdate {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetDislikeCount sets the "dislike_count" field.
func (_u *CommentUpdate) SetDislikeCount(v int) *CommentUpdate {
	_u.mutation.ResetDislikeCount()
	_u.mutation.SetDislikeCount(v)
	return _u
}

// SetNillableDislikeCount sets the "dislike_count" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableDislikeCount(v *int) *CommentUpdate {
	if v != nil {
		_u.SetDislikeCount(*v)
	}
	return _u
}

// AddDislikeCount adds value to the "dislike_count" field.
func (_u *CommentUpdate) AddDislikeCount(v int) *CommentUpdate {
	_u.mutation.AddDislikeCount(v)
	return _u
}

// SetIsSelected sets the "is_selected" field.
func (_u *CommentUpdate) SetIsSelected(v bool) *CommentUpdate {
	_u.mutation.SetIsSelected(v)
	return _u
}

// SetNillableIsSelected sets the "is_selected" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableIsSelected(v *bool) *CommentUpdate {
	if v != nil {
		_u.SetIsSelected(*v)
	}
	return _u
}

// SetIsPinned sets the "is_pinned" field.
func (_u *CommentUpdate) SetIsPinned(v bool) *CommentUpdate {
	_u.mutation.SetIsPinned(v)
	return _u
}

// SetNillableIsPinned sets the "is_pinned" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableIsPinned(v *bool) *CommentUpdate {
	if v != nil {
		_u.SetIsPinned(*v)
	}
	return _u
}

// SetCommenterIP sets the "commenter_ip" field.
func (_u *CommentUpdate) SetCommenterIP(v string) *CommentUpdate {
	_u.mutation.SetCommenterIP(v)
	return _u
}

// SetNillableCommenterIP sets the "commenter_ip" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableCommenterIP(v *string) *CommentUpdate {
	if v != nil {
		_u.SetCommenterIP(*v)
	}
	return _u
}

// ClearCommenterIP clears the value of the "commenter_ip" field.
func (_u *CommentUpdate) ClearCommenterIP() *CommentUpdate {
	_u.mutation.ClearCommenterIP()
	return _u
}

// SetDeviceInfo sets the "device_info" field.
func (_u *CommentUpdate) SetDeviceInfo(v string) *CommentUpdate {
	_u.mutation.SetDeviceInfo(v)
	return _u
}

// SetNillableDeviceInfo sets the "device_info" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableDeviceInfo(v *string) *CommentUpdate {
	if v != nil {
		_u.SetDeviceInfo(*v)
	}
	return _u
}

// ClearDeviceInfo clears the value of the "device_info" field.
func (_u *CommentUpdate) ClearDeviceInfo() *CommentUpdate {
	_u.mutation.ClearDeviceInfo()
	return _u
}

// Mutation returns the CommentMutation object of the builder.
func (_u *CommentUpdate) Mutation() *CommentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CommentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := comment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommentUpdate) check() error {
	if v, ok := _u.mutation.PostID(); ok {
		if err := comment.PostIDValidator(v); err != nil {
			return &ValidationError{Name: "post_id", err: fmt.Errorf(`ent: validator failed for field "Comment.post_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := comment.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Comment.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := comment.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Comment.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LikeCount(); ok {
		if err := comment.LikeCountValidator(v); err != nil {
			return &ValidationError{Name: "like_count", err: fmt.Errorf(`ent: validator failed for field "Comment.like_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DislikeCount(); ok {
		if err := comment.DislikeCountValidator(v); err != nil {
			return &ValidationError{Name: "dislike_count", err: fmt.Errorf(`ent: validator failed for field "Comment.dislike_count": %w`, err)}
		}
	}
	return nil
}

func (_u *CommentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(comment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PostID(); ok {
		_spec.SetField(comment.FieldPostID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPostID(); ok {
		_spec.AddField(comment.FieldPostID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(comment.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(comment.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(comment.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(comment.FieldParentID, field.TypeInt, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(comment.FieldParentID, field.TypeInt)
	}
	if value, ok := _u.mutation.ReplyToUserID(); ok {
		_spec.SetField(comment.FieldReplyToUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReplyToUserID(); ok {
		_spec.AddField(comment.FieldReplyToUserID, field.TypeInt, value)
	}
	if _u.mutation.ReplyToUserIDCleared() {
		_spec.ClearField(comment.FieldReplyToUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(comment.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(comment.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(comment.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DislikeCount(); ok {
		_spec.SetField(comment.FieldDislikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDislikeCount(); ok {
		_spec.AddField(comment.FieldDislikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsSelected(); ok {
		_spec.SetField(comment.FieldIsSelected, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPinned(); ok {
		_spec.SetField(comment.FieldIsPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CommenterIP(); ok {
		_spec.SetField(comment.FieldCommenterIP, field.TypeString, value)
	}
	if _u.mutation.CommenterIPCleared() {
		_spec.ClearField(comment.FieldCommenterIP, field.TypeString)
	}
	if value, ok := _u.mutation.DeviceInfo(); ok {
		_spec.SetField(comment.FieldDeviceInfo, field.TypeString, value)
	}
	if _u.mutation.DeviceInfoCleared() {
		_spec.ClearField(comment.FieldDeviceInfo, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommentUpdateOne is the builder for updating a single Comment entity.
type CommentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommentUpdateOne) SetUpdatedAt(v time.Time) *CommentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPostID sets the "post_id" field.
func (_u *CommentUpdateOne) SetPostID(v int) *CommentUpdateOne {
	_u.mutation.ResetPostID()
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillablePostID(v *int) *CommentUpdateOne {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// AddPostID adds value to the "post_id" field.
func (_u *CommentUpdateOne) AddPostID(v int) *CommentUpdateOne {
	_u.mutation.AddPostID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CommentUpdateOne) SetUserID(v int) *CommentUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableUserID(v *int) *CommentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CommentUpdateOne) AddUserID(v int) *CommentUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *CommentUpdateOne) SetParentID(v int) *CommentUpdateOne {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableParentID(v *int) *CommentUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *CommentUpdateOne) AddParentID(v int) *CommentUpdateOne {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *CommentUpdateOne) ClearParentID() *CommentUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetReplyToUserID sets the "reply_to_user_id" field.
func (_u *CommentUpdateOne) SetReplyToUserID(v int) *CommentUpdateOne {
	_u.mutation.ResetReplyToUserID()
	_u.mutation.SetReplyToUserID(v)
	return _u
}

// SetNillableReplyToUserID sets the "reply_to_user_id" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableReplyToUserID(v *int) *CommentUpdateOne {
	if v != nil {
		_u.SetReplyToUserID(*v)
	}
	return _u
}

// AddReplyToUserID adds value to the "reply_to_user_id" field.
func (_u *CommentUpdateOne) AddReplyToUserID(v int) *CommentUpdateOne {
	_u.mutation.AddReplyToUserID(v)
	return _u
}

// ClearReplyToUserID clears the value of the "reply_to_user_id" field.
func (_u *CommentUpdateOne) ClearReplyToUserID() *CommentUpdateOne {
	_u.mutation.ClearReplyToUserID()
	return _u
}

// SetContent sets the "content" field.
func (_u *CommentUpdateOne) SetContent(v string) *CommentUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableContent(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *CommentUpdateOne) SetLikeCount(v int) *CommentUpdateOne {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableLikeCount(v *int) *CommentUpdateOne {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *CommentUpdateOne) AddLikeCount(v int) *CommentUpdateOne {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetDislikeCount sets the "dislike_count" field.
func (_u *CommentUpdateOne) SetDislikeCount(v int) *CommentUpdateOne {
	_u.mutation.ResetDislikeCount()
	_u.mutation.SetDislikeCount(v)
	return _u
}

// SetNillableDislikeCount sets the "dislike_count" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableDislikeCount(v *int) *CommentUpdateOne {
	if v != nil {
		_u.SetDislikeCount(*v)
	}
	return _u
}

// AddDislikeCount adds value to the "dislike_count" field.
func (_u *CommentUpdateOne) AddDislikeCount(v int) *CommentUpdateOne {
	_u.mutation.AddDislikeCount(v)
	return _u
}

// SetIsSelected sets the "is_selected" field.
func (_u *CommentUpdateOne) SetIsSelected(v bool) *CommentUpdateOne {
	_u.mutation.SetIsSelected(v)
	return _u
}

// SetNillableIsSelected sets the "is_selected" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableIsSelected(v *bool) *CommentUpdateOne {
	if v != nil {
		_u.SetIsSelected(*v)
	}
	return _u
}

// SetIsPinned sets the "is_pinned" field.
func (_u *CommentUpdateOne) SetIsPinned(v bool) *CommentUpdateOne {
	_u.mutation.SetIsPinned(v)
	return _u
}

// SetNillableIsPinned sets the "is_pinned" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableIsPinned(v *bool) *CommentUpdateOne {
	if v != nil {
		_u.SetIsPinned(*v)
	}
	return _u
}

// SetCommenterIP sets the "commenter_ip" field.
func (_u *CommentUpdateOne) SetCommenterIP(v string) *CommentUpdateOne {
	_u.mutation.SetCommenterIP(v)
	return _u
}

// SetNillableCommenterIP sets the "commenter_ip" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableCommenterIP(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetCommenterIP(*v)
	}
	return _u
}

// ClearCommenterIP clears the value of the "commenter_ip" field.
func (_u *CommentUpdateOne) ClearCommenterIP() *CommentUpdateOne {
	_u.mutation.ClearCommenterIP()
	return _u
}

// SetDeviceInfo sets the "device_info" field.
func (_u *CommentUpdateOne) SetDeviceInfo(v string) *CommentUpdateOne {
	_u.mutation.SetDeviceInfo(v)
	return _u
}

// SetNillableDeviceInfo sets the "device_info" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableDeviceInfo(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetDeviceInfo(*v)
	}
	return _u
}

// ClearDeviceInfo clears the value of the "device_info" field.
func (_u *CommentUpdateOne) ClearDeviceInfo() *CommentUpdateOne {
	_u.mutation.ClearDeviceInfo()
	return _u
}

// Mutation returns the CommentMutation object of the builder.
func (_u *CommentUpdateOne) Mutation() *CommentMutation {
	return _u.mutation
}

// Where appends a list predicates to the CommentUpdate builder.
func (_u *CommentUpdateOne) Where(ps ...predicate.Comment) *CommentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommentUpdateOne) Select(field string, fields ...string) *CommentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Comment entity.
func (_u *CommentUpdateOne) Save(ctx context.Context) (*Comment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentUpdateOne) SaveX(ctx context.Context) *Comment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CommentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := comment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommentUpdateOne) check() error {
	if v, ok := _u.mutation.PostID(); ok {
		if err := comment.PostIDValidator(v); err != nil {
			return &ValidationError{Name: "post_id", err: fmt.Errorf(`ent: validator failed for field "Comment.post_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := comment.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Comment.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := comment.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Comment.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LikeCount(); ok {
		if err := comment.LikeCountValidator(v); err != nil {
			return &ValidationError{Name: "like_count", err: fmt.Errorf(`ent: validator failed for field "Comment.like_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DislikeCount(); ok {
		if err := comment.DislikeCountValidator(v); err != nil {
			return &ValidationError{Name: "dislike_count", err: fmt.Errorf(`ent: validator failed for field "Comment.dislike_count": %w`, err)}
		}
	}
	return nil
}

func (_u *CommentUpdateOne) sqlSave(ctx context.Context) (_node *Comment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Comment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, comment.FieldID)
		for _, f := range fields {
			if !comment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != comment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(comment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PostID(); ok {
		_spec.SetField(comment.FieldPostID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPostID(); ok {
		_spec.AddField(comment.FieldPostID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(comment.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(comment.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(comment.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(comment.FieldParentID, field.TypeInt, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(comment.FieldParentID, field.TypeInt)
	}
	if value, ok := _u.mutation.ReplyToUserID(); ok {
		_spec.SetField(comment.FieldReplyToUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReplyToUserID(); ok {
		_spec.AddField(comment.FieldReplyToUserID, field.TypeInt, value)
	}
	if _u.mutation.ReplyToUserIDCleared() {
		_spec.ClearField(comment.FieldReplyToUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(comment.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(comment.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(comment.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DislikeCount(); ok {
		_spec.SetField(comment.FieldDislikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDislikeCount(); ok {
		_spec.AddField(comment.FieldDislikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsSelected(); ok {
		_spec.SetField(comment.FieldIsSelected, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPinned(); ok {
		_spec.SetField(comment.FieldIsPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CommenterIP(); ok {
		_spec.SetField(comment.FieldCommenterIP, field.TypeString, value)
	}
	if _u.mutation.CommenterIPCleared() {
		_spec.ClearField(comment.FieldCommenterIP, field.TypeString)
	}
	if value, ok := _u.mutation.DeviceInfo(); ok {
		_spec.SetField(comment.FieldDeviceInfo, field.TypeString, value)
	}
	if _u.mutation.DeviceInfoCleared() {
		_spec.ClearField(comment.FieldDeviceInfo, field.TypeString)
	}
	_node = &Comment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
