// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PokeForum/PokeForum/ent/comment"
	"github.com/PokeForum/PokeForum/ent/commentaction"
	"github.com/PokeForum/PokeForum/ent/predicate"
	"github.com/PokeForum/PokeForum/ent/user"
)

// CommentActionUpdate is the builder for updating CommentAction entities.
type CommentActionUpdate struct {
	config
	hooks    []Hook
	mutation *CommentActionMutation
}

// Where appends a list predicates to the CommentActionUpdate builder.
func (_u *CommentActionUpdate) Where(ps ...predicate.CommentAction) *CommentActionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommentActionUpdate) SetUpdatedAt(v time.Time) *CommentActionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CommentActionUpdate) SetUserID(v int) *CommentActionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CommentActionUpdate) SetNillableUserID(v *int) *CommentActionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCommentID sets the "comment_id" field.
func (_u *CommentActionUpdate) SetCommentID(v int) *CommentActionUpdate {
	_u.mutation.SetCommentID(v)
	return _u
}

// SetNillableCommentID sets the "comment_id" field if the given value is not nil.
func (_u *CommentActionUpdate) SetNillableCommentID(v *int) *CommentActionUpdate {
	if v != nil {
		_u.SetCommentID(*v)
	}
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *CommentActionUpdate) SetActionType(v commentaction.ActionType) *CommentActionUpdate {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *CommentActionUpdate) SetNillableActionType(v *commentaction.ActionType) *CommentActionUpdate {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CommentActionUpdate) SetUser(v *User) *CommentActionUpdate {
	return _u.SetUserID(v.ID)
}

// SetComment sets the "comment" edge to the Comment entity.
func (_u *CommentActionUpdate) SetComment(v *Comment) *CommentActionUpdate {
	return _u.SetCommentID(v.ID)
}

// Mutation returns the CommentActionMutation object of the builder.
func (_u *CommentActionUpdate) Mutation() *CommentActionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CommentActionUpdate) ClearUser() *CommentActionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearComment clears the "comment" edge to the Comment entity.
func (_u *CommentActionUpdate) ClearComment() *CommentActionUpdate {
	_u.mutation.ClearComment()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommentActionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentActionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommentActionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentActionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CommentActionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := commentaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommentActionUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := commentaction.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CommentAction.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CommentID(); ok {
		if err := commentaction.CommentIDValidator(v); err != nil {
			return &ValidationError{Name: "comment_id", err: fmt.Errorf(`ent: validator failed for field "CommentAction.comment_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActionType(); ok {
		if err := commentaction.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "CommentAction.action_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CommentAction.user"`)
	}
	if _u.mutation.CommentCleared() && len(_u.mutation.CommentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CommentAction.comment"`)
	}
	return nil
}

func (_u *CommentActionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(commentaction.Table, commentaction.Columns, sqlgraph.NewFieldSpec(commentaction.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(commentaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(commentaction.FieldActionType, field.TypeEnum, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commentaction.UserTable,
			Columns: []string{commentaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commentaction.UserTable,
			Columns: []string{commentaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commentaction.CommentTable,
			Columns: []string{commentaction.CommentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commentaction.CommentTable,
			Columns: []string{commentaction.CommentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commentaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommentActionUpdateOne is the builder for updating a single CommentAction entity.
type CommentActionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommentActionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommentActionUpdateOne) SetUpdatedAt(v time.Time) *CommentActionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CommentActionUpdateOne) SetUserID(v int) *CommentActionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CommentActionUpdateOne) SetNillableUserID(v *int) *CommentActionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCommentID sets the "comment_id" field.
func (_u *CommentActionUpdateOne) SetCommentID(v int) *CommentActionUpdateOne {
	_u.mutation.SetCommentID(v)
	return _u
}

// SetNillableCommentID sets the "comment_id" field if the given value is not nil.
func (_u *CommentActionUpdateOne) SetNillableCommentID(v *int) *CommentActionUpdateOne {
	if v != nil {
		_u.SetCommentID(*v)
	}
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *CommentActionUpdateOne) SetActionType(v commentaction.ActionType) *CommentActionUpdateOne {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *CommentActionUpdateOne) SetNillableActionType(v *commentaction.ActionType) *CommentActionUpdateOne {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CommentActionUpdateOne) SetUser(v *User) *CommentActionUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetComment sets the "comment" edge to the Comment entity.
func (_u *CommentActionUpdateOne) SetComment(v *Comment) *CommentActionUpdateOne {
	return _u.SetCommentID(v.ID)
}

// Mutation returns the CommentActionMutation object of the builder.
func (_u *CommentActionUpdateOne) Mutation() *CommentActionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CommentActionUpdateOne) ClearUser() *CommentActionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearComment clears the "comment" edge to the Comment entity.
func (_u *CommentActionUpdateOne) ClearComment() *CommentActionUpdateOne {
	_u.mutation.ClearComment()
	return _u
}

// Where appends a list predicates to the CommentActionUpdate builder.
func (_u *CommentActionUpdateOne) Where(ps ...predicate.CommentAction) *CommentActionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommentActionUpdateOne) Select(field string, fields ...string) *CommentActionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CommentAction entity.
func (_u *CommentActionUpdateOne) Save(ctx context.Context) (*CommentAction, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentActionUpdateOne) SaveX(ctx context.Context) *CommentAction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommentActionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentActionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CommentActionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := commentaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommentActionUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := commentaction.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CommentAction.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CommentID(); ok {
		if err := commentaction.CommentIDValidator(v); err != nil {
			return &ValidationError{Name: "comment_id", err: fmt.Errorf(`ent: validator failed for field "CommentAction.comment_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActionType(); ok {
		if err := commentaction.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "CommentAction.action_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CommentAction.user"`)
	}
	if _u.mutation.CommentCleared() && len(_u.mutation.CommentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CommentAction.comment"`)
	}
	return nil
}

func (_u *CommentActionUpdateOne) sqlSave(ctx context.Context) (_node *CommentAction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(commentaction.Table, commentaction.Columns, sqlgraph.NewFieldSpec(commentaction.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CommentAction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commentaction.FieldID)
		for _, f := range fields {
			if !commentaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != commentaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(commentaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(commentaction.FieldActionType, field.TypeEnum, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commentaction.UserTable,
			Columns: []string{commentaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commentaction.UserTable,
			Columns: []string{commentaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commentaction.CommentTable,
			Columns: []string{commentaction.CommentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commentaction.CommentTable,
			Columns: []string{commentaction.CommentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CommentAction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commentaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
