// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PokeForum/PokeForum/ent/invitationcode"
	"github.com/PokeForum/PokeForum/ent/predicate"
)

// InvitationCodeUpdate is the builder for updating InvitationCode entities.
type InvitationCodeUpdate struct {
	config
	hooks    []Hook
	mutation *InvitationCodeMutation
}

// Where appends a list predicates to the InvitationCodeUpdate builder.
func (_u *InvitationCodeUpdate) Where(ps ...predicate.InvitationCode) *InvitationCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvitationCodeUpdate) SetUpdatedAt(v time.Time) *InvitationCodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *InvitationCodeUpdate) SetCode(v string) *InvitationCodeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *InvitationCodeUpdate) SetNillableCode(v *string) *InvitationCodeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetCreatorID sets the "creator_id" field.
func (_u *InvitationCodeUpdate) SetCreatorID(v int) *InvitationCodeUpdate {
	_u.mutation.ResetCreatorID()
	_u.mutation.SetCreatorID(v)
	return _u
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (_u *InvitationCodeUpdate) SetNillableCreatorID(v *int) *InvitationCodeUpdate {
	if v != nil {
		_u.SetCreatorID(*v)
	}
	return _u
}

// AddCreatorID adds value to the "creator_id" field.
func (_u *InvitationCodeUpdate) AddCreatorID(v int) *InvitationCodeUpdate {
	_u.mutation.AddCreatorID(v)
	return _u
}

// SetUsedByID sets the "used_by_id" field.
func (_u *InvitationCodeUpdate) SetUsedByID(v int) *InvitationCodeUpdate {
	_u.mutation.ResetUsedByID()
	_u.mutation.SetUsedByID(v)
	return _u
}

// SetNillableUsedByID sets the "used_by_id" field if the given value is not nil.
func (_u *InvitationCodeUpdate) SetNillableUsedByID(v *int) *InvitationCodeUpdate {
	if v != nil {
		_u.SetUsedByID(*v)
	}
	return _u
}

// AddUsedByID adds value to the "used_by_id" field.
func (_u *InvitationCodeUpdate) AddUsedByID(v int) *InvitationCodeUpdate {
	_u.mutation.AddUsedByID(v)
	return _u
}

// ClearUsedByID clears the value of the "used_by_id" field.
func (_u *InvitationCodeUpdate) ClearUsedByID() *InvitationCodeUpdate {
	_u.mutation.ClearUsedByID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvitationCodeUpdate) SetStatus(v invitationcode.Status) *InvitationCodeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvitationCodeUpdate) SetNillableStatus(v *invitationcode.Status) *InvitationCodeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGenerationMode sets the "generation_mode" field.
func (_u *InvitationCodeUpdate) SetGenerationMode(v invitationcode.GenerationMode) *InvitationCodeUpdate {
	_u.mutation.SetGenerationMode(v)
	return _u
}

// SetNillableGenerationMode sets the "generation_mode" field if the given value is not nil.
func (_u *InvitationCodeUpdate) SetNillableGenerationMode(v *invitationcode.GenerationMode) *InvitationCodeUpdate {
	if v != nil {
		_u.SetGenerationMode(*v)
	}
	return _u
}

// SetCostAmount sets the "cost_amount" field.
func (_u *InvitationCodeUpdate) SetCostAmount(v int) *InvitationCodeUpdate {
	_u.mutation.ResetCostAmount()
	_u.mutation.SetCostAmount(v)
	return _u
}

// SetNillableCostAmount sets the "cost_amount" field if the given value is not nil.
func (_u *InvitationCodeUpdate) SetNillableCostAmount(v *int) *InvitationCodeUpdate {
	if v != nil {
		_u.SetCostAmount(*v)
	}
	return _u
}

// AddCostAmount adds value to the "cost_amount" field.
func (_u *InvitationCodeUpdate) AddCostAmount(v int) *InvitationCodeUpdate {
	_u.mutation.AddCostAmount(v)
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *InvitationCodeUpdate) SetUsedAt(v time.Time) *InvitationCodeUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *InvitationCodeUpdate) SetNillableUsedAt(v *time.Time) *InvitationCodeUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *InvitationCodeUpdate) ClearUsedAt() *InvitationCodeUpdate {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *InvitationCodeUpdate) SetExpiresAt(v time.Time) *InvitationCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *InvitationCodeUpdate) SetNillableExpiresAt(v *time.Time) *InvitationCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *InvitationCodeUpdate) ClearExpiresAt() *InvitationCodeUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUsedIP sets the "used_ip" field.
func (_u *InvitationCodeUpdate) SetUsedIP(v string) *InvitationCodeUpdate {
	_u.mutation.SetUsedIP(v)
	return _u
}

// SetNillableUsedIP sets the "used_ip" field if the given value is not nil.
func (_u *InvitationCodeUpdate) SetNillableUsedIP(v *string) *InvitationCodeUpdate {
	if v != nil {
		_u.SetUsedIP(*v)
	}
	return _u
}

// ClearUsedIP clears the value of the "used_ip" field.
func (_u *InvitationCodeUpdate) ClearUsedIP() *InvitationCodeUpdate {
	_u.mutation.ClearUsedIP()
	return _u
}

// SetUsedUserAgent sets the "used_user_agent" field.
func (_u *InvitationCodeUpdate) SetUsedUserAgent(v string) *InvitationCodeUpdate {
	_u.mutation.SetUsedUserAgent(v)
	return _u
}

// SetNillableUsedUserAgent sets the "used_user_agent" field if the given value is not nil.
func (_u *InvitationCodeUpdate) SetNillableUsedUserAgent(v *string) *InvitationCodeUpdate {
	if v != nil {
		_u.SetUsedUserAgent(*v)
	}
	return _u
}

// ClearUsedUserAgent clears the value of the "used_user_agent" field.
func (_u *InvitationCodeUpdate) ClearUsedUserAgent() *InvitationCodeUpdate {
	_u.mutation.ClearUsedUserAgent()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *InvitationCodeUpdate) SetRemark(v string) *InvitationCodeUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *InvitationCodeUpdate) SetNillableRemark(v *string) *InvitationCodeUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *InvitationCodeUpdate) ClearRemark() *InvitationCodeUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// Mutation returns the InvitationCodeMutation object of the builder.
func (_u *InvitationCodeUpdate) Mutation() *InvitationCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvitationCodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvitationCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvitationCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvitationCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvitationCodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invitationcode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvitationCodeUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := invitationcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "InvitationCode.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatorID(); ok {
		if err := invitationcode.CreatorIDValidator(v); err != nil {
			return &ValidationError{Name: "creator_id", err: fmt.Errorf(`ent: validator failed for field "InvitationCode.creator_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invitationcode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvitationCode.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GenerationMode(); ok {
		if err := invitationcode.GenerationModeValidator(v); err != nil {
			return &ValidationError{Name: "generation_mode", err: fmt.Errorf(`ent: validator failed for field "InvitationCode.generation_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CostAmount(); ok {
		if err := invitationcode.CostAmountValidator(v); err != nil {
			return &ValidationError{Name: "cost_amount", err: fmt.Errorf(`ent: validator failed for field "InvitationCode.cost_amount": %w`, err)}
		}
	}
	return nil
}

func (_u *InvitationCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitationcode.Table, invitationcode.Columns, sqlgraph.NewFieldSpec(invitationcode.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invitationcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(invitationcode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatorID(); ok {
		_spec.SetField(invitationcode.FieldCreatorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatorID(); ok {
		_spec.AddField(invitationcode.FieldCreatorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsedByID(); ok {
		_spec.SetField(invitationcode.FieldUsedByID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedByID(); ok {
		_spec.AddField(invitationcode.FieldUsedByID, field.TypeInt, value)
	}
	if _u.mutation.UsedByIDCleared() {
		_spec.ClearField(invitationcode.FieldUsedByID, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invitationcode.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GenerationMode(); ok {
		_spec.SetField(invitationcode.FieldGenerationMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CostAmount(); ok {
		_spec.SetField(invitationcode.FieldCostAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCostAmount(); ok {
		_spec.AddField(invitationcode.FieldCostAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(invitationcode.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(invitationcode.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(invitationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(invitationcode.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UsedIP(); ok {
		_spec.SetField(invitationcode.FieldUsedIP, field.TypeString, value)
	}
	if _u.mutation.UsedIPCleared() {
		_spec.ClearField(invitationcode.FieldUsedIP, field.TypeString)
	}
	if value, ok := _u.mutation.UsedUserAgent(); ok {
		_spec.SetField(invitationcode.FieldUsedUserAgent, field.TypeString, value)
	}
	if _u.mutation.UsedUserAgentCleared() {
		_spec.ClearField(invitationcode.FieldUsedUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(invitationcode.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(invitationcode.FieldRemark, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvitationCodeUpdateOne is the builder for updating a single InvitationCode entity.
type InvitationCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvitationCodeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvitationCodeUpdateOne) SetUpdatedAt(v time.Time) *InvitationCodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *InvitationCodeUpdateOne) SetCode(v string) *InvitationCodeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *InvitationCodeUpdateOne) SetNillableCode(v *string) *InvitationCodeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetCreatorID sets the "creator_id" field.
func (_u *InvitationCodeUpdateOne) SetCreatorID(v int) *InvitationCodeUpdateOne {
	_u.mutation.ResetCreatorID()
	_u.mutation.SetCreatorID(v)
	return _u
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (_u *InvitationCodeUpdateOne) SetNillableCreatorID(v *int) *InvitationCodeUpdateOne {
	if v != nil {
		_u.SetCreatorID(*v)
	}
	return _u
}

// AddCreatorID adds value to the "creator_id" field.
func (_u *InvitationCodeUpdateOne) AddCreatorID(v int) *InvitationCodeUpdateOne {
	_u.mutation.AddCreatorID(v)
	return _u
}

// SetUsedByID sets the "used_by_id" field.
func (_u *InvitationCodeUpdateOne) SetUsedByID(v int) *InvitationCodeUpdateOne {
	_u.mutation.ResetUsedByID()
	_u.mutation.SetUsedByID(v)
	return _u
}

// SetNillableUsedByID sets the "used_by_id" field if the given value is not nil.
func (_u *InvitationCodeUpdateOne) SetNillableUsedByID(v *int) *InvitationCodeUpdateOne {
	if v != nil {
		_u.SetUsedByID(*v)
	}
	return _u
}

// AddUsedByID adds value to the "used_by_id" field.
func (_u *InvitationCodeUpdateOne) AddUsedByID(v int) *InvitationCodeUpdateOne {
	_u.mutation.AddUsedByID(v)
	return _u
}

// ClearUsedByID clears the value of the "used_by_id" field.
func (_u *InvitationCodeUpdateOne) ClearUsedByID() *InvitationCodeUpdateOne {
	_u.mutation.ClearUsedByID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvitationCodeUpdateOne) SetStatus(v invitationcode.Status) *InvitationCodeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvitationCodeUpdateOne) SetNillableStatus(v *invitationcode.Status) *InvitationCodeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGenerationMode sets the "generation_mode" field.
func (_u *InvitationCodeUpdateOne) SetGenerationMode(v invitationcode.GenerationMode) *InvitationCodeUpdateOne {
	_u.mutation.SetGenerationMode(v)
	return _u
}

// SetNillableGenerationMode sets the "generation_mode" field if the given value is not nil.
func (_u *InvitationCodeUpdateOne) SetNillableGenerationMode(v *invitationcode.GenerationMode) *InvitationCodeUpdateOne {
	if v != nil {
		_u.SetGenerationMode(*v)
	}
	return _u
}

// SetCostAmount sets the "cost_amount" field.
func (_u *InvitationCodeUpdateOne) SetCostAmount(v int) *InvitationCodeUpdateOne {
	_u.mutation.ResetCostAmount()
	_u.mutation.SetCostAmount(v)
	return _u
}

// SetNillableCostAmount sets the "cost_amount" field if the given value is not nil.
func (_u *InvitationCodeUpdateOne) SetNillableCostAmount(v *int) *InvitationCodeUpdateOne {
	if v != nil {
		_u.SetCostAmount(*v)
	}
	return _u
}

// AddCostAmount adds value to the "cost_amount" field.
func (_u *InvitationCodeUpdateOne) AddCostAmount(v int) *InvitationCodeUpdateOne {
	_u.mutation.AddCostAmount(v)
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *InvitationCodeUpdateOne) SetUsedAt(v time.Time) *InvitationCodeUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *InvitationCodeUpdateOne) SetNillableUsedAt(v *time.Time) *InvitationCodeUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *InvitationCodeUpdateOne) ClearUsedAt() *InvitationCodeUpdateOne {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *InvitationCodeUpdateOne) SetExpiresAt(v time.Time) *InvitationCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *InvitationCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *InvitationCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *InvitationCodeUpdateOne) ClearExpiresAt() *InvitationCodeUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUsedIP sets the "used_ip" field.
func (_u *InvitationCodeUpdateOne) SetUsedIP(v string) *InvitationCodeUpdateOne {
	_u.mutation.SetUsedIP(v)
	return _u
}

// SetNillableUsedIP sets the "used_ip" field if the given value is not nil.
func (_u *InvitationCodeUpdateOne) SetNillableUsedIP(v *string) *InvitationCodeUpdateOne {
	if v != nil {
		_u.SetUsedIP(*v)
	}
	return _u
}

// ClearUsedIP clears the value of the "used_ip" field.
func (_u *InvitationCodeUpdateOne) ClearUsedIP() *InvitationCodeUpdateOne {
	_u.mutation.ClearUsedIP()
	return _u
}

// SetUsedUserAgent sets the "used_user_agent" field.
func (_u *InvitationCodeUpdateOne) SetUsedUserAgent(v string) *InvitationCodeUpdateOne {
	_u.mutation.SetUsedUserAgent(v)
	return _u
}

// SetNillableUsedUserAgent sets the "used_user_agent" field if the given value is not nil.
func (_u *InvitationCodeUpdateOne) SetNillableUsedUserAgent(v *string) *InvitationCodeUpdateOne {
	if v != nil {
		_u.SetUsedUserAgent(*v)
	}
	return _u
}

// ClearUsedUserAgent clears the value of the "used_user_agent" field.
func (_u *InvitationCodeUpdateOne) ClearUsedUserAgent() *InvitationCodeUpdateOne {
	_u.mutation.ClearUsedUserAgent()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *InvitationCodeUpdateOne) SetRemark(v string) *InvitationCodeUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *InvitationCodeUpdateOne) SetNillableRemark(v *string) *InvitationCodeUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *InvitationCodeUpdateOne) ClearRemark() *InvitationCodeUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// Mutation returns the InvitationCodeMutation object of the builder.
func (_u *InvitationCodeUpdateOne) Mutation() *InvitationCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the InvitationCodeUpdate builder.
func (_u *InvitationCodeUpdateOne) Where(ps ...predicate.InvitationCode) *InvitationCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvitationCodeUpdateOne) Select(field string, fields ...string) *InvitationCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvitationCode entity.
func (_u *InvitationCodeUpdateOne) Save(ctx context.Context) (*InvitationCode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvitationCodeUpdateOne) SaveX(ctx context.Context) *InvitationCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvitationCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvitationCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvitationCodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invitationcode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvitationCodeUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := invitationcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "InvitationCode.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatorID(); ok {
		if err := invitationcode.CreatorIDValidator(v); err != nil {
			return &ValidationError{Name: "creator_id", err: fmt.Errorf(`ent: validator failed for field "InvitationCode.creator_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invitationcode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvitationCode.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GenerationMode(); ok {
		if err := invitationcode.GenerationModeValidator(v); err != nil {
			return &ValidationError{Name: "generation_mode", err: fmt.Errorf(`ent: validator failed for field "InvitationCode.generation_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CostAmount(); ok {
		if err := invitationcode.CostAmountValidator(v); err != nil {
			return &ValidationError{Name: "cost_amount", err: fmt.Errorf(`ent: validator failed for field "InvitationCode.cost_amount": %w`, err)}
		}
	}
	return nil
}

func (_u *InvitationCodeUpdateOne) sqlSave(ctx context.Context) (_node *InvitationCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitationcode.Table, invitationcode.Columns, sqlgraph.NewFieldSpec(invitationcode.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvitationCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invitationcode.FieldID)
		for _, f := range fields {
			if !invitationcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invitationcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invitationcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(invitationcode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatorID(); ok {
		_spec.SetField(invitationcode.FieldCreatorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatorID(); ok {
		_spec.AddField(invitationcode.FieldCreatorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsedByID(); ok {
		_spec.SetField(invitationcode.FieldUsedByID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedByID(); ok {
		_spec.AddField(invitationcode.FieldUsedByID, field.TypeInt, value)
	}
	if _u.mutation.UsedByIDCleared() {
		_spec.ClearField(invitationcode.FieldUsedByID, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invitationcode.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GenerationMode(); ok {
		_spec.SetField(invitationcode.FieldGenerationMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CostAmount(); ok {
		_spec.SetField(invitationcode.FieldCostAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCostAmount(); ok {
		_spec.AddField(invitationcode.FieldCostAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(invitationcode.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(invitationcode.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(invitationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(invitationcode.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UsedIP(); ok {
		_spec.SetField(invitationcode.FieldUsedIP, field.TypeString, value)
	}
	if _u.mutation.UsedIPCleared() {
		_spec.ClearField(invitationcode.FieldUsedIP, field.TypeString)
	}
	if value, ok := _u.mutation.UsedUserAgent(); ok {
		_spec.SetField(invitationcode.FieldUsedUserAgent, field.TypeString, value)
	}
	if _u.mutation.UsedUserAgentCleared() {
		_spec.ClearField(invitationcode.FieldUsedUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(invitationcode.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(invitationcode.FieldRemark, field.TypeString)
	}
	_node = &InvitationCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
