// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PokeForum/PokeForum/ent/oauthprovider"
)

// OAuthProviderCreate is the builder for creating a OAuthProvider entity.
type OAuthProviderCreate struct {
	config
	mutation *OAuthProviderMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthProviderCreate) SetCreatedAt(v time.Time) *OAuthProviderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthProviderCreate) SetNillableCreatedAt(v *time.Time) *OAuthProviderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthProviderCreate) SetUpdatedAt(v time.Time) *OAuthProviderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthProviderCreate) SetNillableUpdatedAt(v *time.Time) *OAuthProviderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *OAuthProviderCreate) SetProvider(v oauthprovider.Provider) *OAuthProviderCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthProviderCreate) SetClientID(v string) *OAuthProviderCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_c *OAuthProviderCreate) SetNillableClientID(v *string) *OAuthProviderCreate {
	if v != nil {
		_c.SetClientID(*v)
	}
	return _c
}

// SetClientSecret sets the "client_secret" field.
func (_c *OAuthProviderCreate) SetClientSecret(v string) *OAuthProviderCreate {
	_c.mutation.SetClientSecret(v)
	return _c
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (_c *OAuthProviderCreate) SetNillableClientSecret(v *string) *OAuthProviderCreate {
	if v != nil {
		_c.SetClientSecret(*v)
	}
	return _c
}

// SetAuthURL sets the "auth_url" field.
func (_c *OAuthProviderCreate) SetAuthURL(v string) *OAuthProviderCreate {
	_c.mutation.SetAuthURL(v)
	return _c
}

// SetNillableAuthURL sets the "auth_url" field if the given value is not nil.
func (_c *OAuthProviderCreate) SetNillableAuthURL(v *string) *OAuthProviderCreate {
	if v != nil {
		_c.SetAuthURL(*v)
	}
	return _c
}

// SetTokenURL sets the "token_url" field.
func (_c *OAuthProviderCreate) SetTokenURL(v string) *OAuthProviderCreate {
	_c.mutation.SetTokenURL(v)
	return _c
}

// SetNillableTokenURL sets the "token_url" field if the given value is not nil.
func (_c *OAuthProviderCreate) SetNillableTokenURL(v *string) *OAuthProviderCreate {
	if v != nil {
		_c.SetTokenURL(*v)
	}
	return _c
}

// SetUserInfoURL sets the "user_info_url" field.
func (_c *OAuthProviderCreate) SetUserInfoURL(v string) *OAuthProviderCreate {
	_c.mutation.SetUserInfoURL(v)
	return _c
}

// SetNillableUserInfoURL sets the "user_info_url" field if the given value is not nil.
func (_c *OAuthProviderCreate) SetNillableUserInfoURL(v *string) *OAuthProviderCreate {
	if v != nil {
		_c.SetUserInfoURL(*v)
	}
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OAuthProviderCreate) SetScopes(v []string) *OAuthProviderCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetExtraConfig sets the "extra_config" field.
func (_c *OAuthProviderCreate) SetExtraConfig(v map[string]interface{}) *OAuthProviderCreate {
	_c.mutation.SetExtraConfig(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *OAuthProviderCreate) SetEnabled(v bool) *OAuthProviderCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *OAuthProviderCreate) SetNillableEnabled(v *bool) *OAuthProviderCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *OAuthProviderCreate) SetSortOrder(v int) *OAuthProviderCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *OAuthProviderCreate) SetNillableSortOrder(v *int) *OAuthProviderCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthProviderCreate) SetID(v int) *OAuthProviderCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OAuthProviderMutation object of the builder.
func (_c *OAuthProviderCreate) Mutation() *OAuthProviderMutation {
	return _c.mutation
}

// Save creates the OAuthProvider in the database.
func (_c *OAuthProviderCreate) Save(ctx context.Context) (*OAuthProvider, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthProviderCreate) SaveX(ctx context.Context) *OAuthProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthProviderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthprovider.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthprovider.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := oauthprovider.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := oauthprovider.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthProviderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthProvider.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthProvider.updated_at"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "OAuthProvider.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := oauthprovider.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "OAuthProvider.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "OAuthProvider.enabled"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "OAuthProvider.sort_order"`)}
	}
	if v, ok := _c.mutation.SortOrder(); ok {
		if err := oauthprovider.SortOrderValidator(v); err != nil {
			return &ValidationError{Name: "sort_order", err: fmt.Errorf(`ent: validator failed for field "OAuthProvider.sort_order": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := oauthprovider.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "OAuthProvider.id": %w`, err)}
		}
	}
	return nil
}

func (_c *OAuthProviderCreate) sqlSave(ctx context.Context) (*OAuthProvider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthProviderCreate) createSpec() (*OAuthProvider, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthProvider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthprovider.Table, sqlgraph.NewFieldSpec(oauthprovider.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthprovider.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthprovider.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(oauthprovider.FieldProvider, field.TypeEnum, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthprovider.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientSecret(); ok {
		_spec.SetField(oauthprovider.FieldClientSecret, field.TypeString, value)
		_node.ClientSecret = value
	}
	if value, ok := _c.mutation.AuthURL(); ok {
		_spec.SetField(oauthprovider.FieldAuthURL, field.TypeString, value)
		_node.AuthURL = value
	}
	if value, ok := _c.mutation.TokenURL(); ok {
		_spec.SetField(oauthprovider.FieldTokenURL, field.TypeString, value)
		_node.TokenURL = value
	}
	if value, ok := _c.mutation.UserInfoURL(); ok {
		_spec.SetField(oauthprovider.FieldUserInfoURL, field.TypeString, value)
		_node.UserInfoURL = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauthprovider.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.ExtraConfig(); ok {
		_spec.SetField(oauthprovider.FieldExtraConfig, field.TypeJSON, value)
		_node.ExtraConfig = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(oauthprovider.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(oauthprovider.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	return _node, _spec
}

// OAuthProviderCreateBulk is the builder for creating many OAuthProvider entities in bulk.
type OAuthProviderCreateBulk struct {
	config
	err      error
	builders []*OAuthProviderCreate
}

// Save creates the OAuthProvider entities in the database.
func (_c *OAuthProviderCreateBulk) Save(ctx context.Context) ([]*OAuthProvider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthProvider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthProviderCreateBulk) SaveX(ctx context.Context) []*OAuthProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
