// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PokeForum/PokeForum/ent/post"
)

// PostCreate is the builder for creating a Post entity.
type PostCreate struct {
	config
	mutation *PostMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PostCreate) SetCreatedAt(v time.Time) *PostCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableCreatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PostCreate) SetUpdatedAt(v time.Time) *PostCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableUpdatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PostCreate) SetUserID(v int) *PostCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCategoryID sets the "category_id" field.
func (_c *PostCreate) SetCategoryID(v int) *PostCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *PostCreate) SetTitle(v string) *PostCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *PostCreate) SetContent(v string) *PostCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetReadPermission sets the "read_permission" field.
func (_c *PostCreate) SetReadPermission(v string) *PostCreate {
	_c.mutation.SetReadPermission(v)
	return _c
}

// SetNillableReadPermission sets the "read_permission" field if the given value is not nil.
func (_c *PostCreate) SetNillableReadPermission(v *string) *PostCreate {
	if v != nil {
		_c.SetReadPermission(*v)
	}
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *PostCreate) SetViewCount(v int) *PostCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *PostCreate) SetNillableViewCount(v *int) *PostCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetLikeCount sets the "like_count" field.
func (_c *PostCreate) SetLikeCount(v int) *PostCreate {
	_c.mutation.SetLikeCount(v)
	return _c
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_c *PostCreate) SetNillableLikeCount(v *int) *PostCreate {
	if v != nil {
		_c.SetLikeCount(*v)
	}
	return _c
}

// SetDislikeCount sets the "dislike_count" field.
func (_c *PostCreate) SetDislikeCount(v int) *PostCreate {
	_c.mutation.SetDislikeCount(v)
	return _c
}

// SetNillableDislikeCount sets the "dislike_count" field if the given value is not nil.
func (_c *PostCreate) SetNillableDislikeCount(v *int) *PostCreate {
	if v != nil {
		_c.SetDislikeCount(*v)
	}
	return _c
}

// SetFavoriteCount sets the "favorite_count" field.
func (_c *PostCreate) SetFavoriteCount(v int) *PostCreate {
	_c.mutation.SetFavoriteCount(v)
	return _c
}

// SetNillableFavoriteCount sets the "favorite_count" field if the given value is not nil.
func (_c *PostCreate) SetNillableFavoriteCount(v *int) *PostCreate {
	if v != nil {
		_c.SetFavoriteCount(*v)
	}
	return _c
}

// SetIsEssence sets the "is_essence" field.
func (_c *PostCreate) SetIsEssence(v bool) *PostCreate {
	_c.mutation.SetIsEssence(v)
	return _c
}

// SetNillableIsEssence sets the "is_essence" field if the given value is not nil.
func (_c *PostCreate) SetNillableIsEssence(v *bool) *PostCreate {
	if v != nil {
		_c.SetIsEssence(*v)
	}
	return _c
}

// SetIsPinned sets the "is_pinned" field.
func (_c *PostCreate) SetIsPinned(v bool) *PostCreate {
	_c.mutation.SetIsPinned(v)
	return _c
}

// SetNillableIsPinned sets the "is_pinned" field if the given value is not nil.
func (_c *PostCreate) SetNillableIsPinned(v *bool) *PostCreate {
	if v != nil {
		_c.SetIsPinned(*v)
	}
	return _c
}

// SetPublishIP sets the "publish_ip" field.
func (_c *PostCreate) SetPublishIP(v string) *PostCreate {
	_c.mutation.SetPublishIP(v)
	return _c
}

// SetNillablePublishIP sets the "publish_ip" field if the given value is not nil.
func (_c *PostCreate) SetNillablePublishIP(v *string) *PostCreate {
	if v != nil {
		_c.SetPublishIP(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PostCreate) SetStatus(v post.Status) *PostCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PostCreate) SetNillableStatus(v *post.Status) *PostCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PostCreate) SetID(v int) *PostCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PostMutation object of the builder.
func (_c *PostCreate) Mutation() *PostMutation {
	return _c.mutation
}

// Save creates the Post in the database.
func (_c *PostCreate) Save(ctx context.Context) (*Post, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PostCreate) SaveX(ctx context.Context) *Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PostCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := post.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := post.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		v := post.DefaultViewCount
		_c.mutation.SetViewCount(v)
	}
	if _, ok := _c.mutation.LikeCount(); !ok {
		v := post.DefaultLikeCount
		_c.mutation.SetLikeCount(v)
	}
	if _, ok := _c.mutation.DislikeCount(); !ok {
		v := post.DefaultDislikeCount
		_c.mutation.SetDislikeCount(v)
	}
	if _, ok := _c.mutation.FavoriteCount(); !ok {
		v := post.DefaultFavoriteCount
		_c.mutation.SetFavoriteCount(v)
	}
	if _, ok := _c.mutation.IsEssence(); !ok {
		v := post.DefaultIsEssence
		_c.mutation.SetIsEssence(v)
	}
	if _, ok := _c.mutation.IsPinned(); !ok {
		v := post.DefaultIsPinned
		_c.mutation.SetIsPinned(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := post.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PostCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Post.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Post.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Post.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := post.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Post.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CategoryID(); !ok {
		return &ValidationError{Name: "category_id", err: errors.New(`ent: missing required field "Post.category_id"`)}
	}
	if v, ok := _c.mutation.CategoryID(); ok {
		if err := post.CategoryIDValidator(v); err != nil {
			return &ValidationError{Name: "category_id", err: fmt.Errorf(`ent: validator failed for field "Post.category_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Post.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Post.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := post.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Post.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`ent: missing required field "Post.view_count"`)}
	}
	if v, ok := _c.mutation.ViewCount(); ok {
		if err := post.ViewCountValidator(v); err != nil {
			return &ValidationError{Name: "view_count", err: fmt.Errorf(`ent: validator failed for field "Post.view_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LikeCount(); !ok {
		return &ValidationError{Name: "like_count", err: errors.New(`ent: missing required field "Post.like_count"`)}
	}
	if v, ok := _c.mutation.LikeCount(); ok {
		if err := post.LikeCountValidator(v); err != nil {
			return &ValidationError{Name: "like_count", err: fmt.Errorf(`ent: validator failed for field "Post.like_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DislikeCount(); !ok {
		return &ValidationError{Name: "dislike_count", err: errors.New(`ent: missing required field "Post.dislike_count"`)}
	}
	if v, ok := _c.mutation.DislikeCount(); ok {
		if err := post.DislikeCountValidator(v); err != nil {
			return &ValidationError{Name: "dislike_count", err: fmt.Errorf(`ent: validator failed for field "Post.dislike_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FavoriteCount(); !ok {
		return &ValidationError{Name: "favorite_count", err: errors.New(`ent: missing required field "Post.favorite_count"`)}
	}
	if v, ok := _c.mutation.FavoriteCount(); ok {
		if err := post.FavoriteCountValidator(v); err != nil {
			return &ValidationError{Name: "favorite_count", err: fmt.Errorf(`ent: validator failed for field "Post.favorite_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsEssence(); !ok {
		return &ValidationError{Name: "is_essence", err: errors.New(`ent: missing required field "Post.is_essence"`)}
	}
	if _, ok := _c.mutation.IsPinned(); !ok {
		return &ValidationError{Name: "is_pinned", err: errors.New(`ent: missing required field "Post.is_pinned"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Post.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := post.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Post.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := post.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Post.id": %w`, err)}
		}
	}
	return nil
}

func (_c *PostCreate) sqlSave(ctx context.Context) (*Post, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PostCreate) createSpec() (*Post, *sqlgraph.CreateSpec) {
	var (
		_node = &Post{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(post.Table, sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(post.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(post.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.CategoryID(); ok {
		_spec.SetField(post.FieldCategoryID, field.TypeInt, value)
		_node.CategoryID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.ReadPermission(); ok {
		_spec.SetField(post.FieldReadPermission, field.TypeString, value)
		_node.ReadPermission = value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(post.FieldViewCount, field.TypeInt, value)
		_node.ViewCount = value
	}
	if value, ok := _c.mutation.LikeCount(); ok {
		_spec.SetField(post.FieldLikeCount, field.TypeInt, value)
		_node.LikeCount = value
	}
	if value, ok := _c.mutation.DislikeCount(); ok {
		_spec.SetField(post.FieldDislikeCount, field.TypeInt, value)
		_node.DislikeCount = value
	}
	if value, ok := _c.mutation.FavoriteCount(); ok {
		_spec.SetField(post.FieldFavoriteCount, field.TypeInt, value)
		_node.FavoriteCount = value
	}
	if value, ok := _c.mutation.IsEssence(); ok {
		_spec.SetField(post.FieldIsEssence, field.TypeBool, value)
		_node.IsEssence = value
	}
	if value, ok := _c.mutation.IsPinned(); ok {
		_spec.SetField(post.FieldIsPinned, field.TypeBool, value)
		_node.IsPinned = value
	}
	if value, ok := _c.mutation.PublishIP(); ok {
		_spec.SetField(post.FieldPublishIP, field.TypeString, value)
		_node.PublishIP = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(post.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	return _node, _spec
}

// PostCreateBulk is the builder for creating many Post entities in bulk.
type PostCreateBulk struct {
	config
	err      error
	builders []*PostCreate
}

// Save creates the Post entities in the database.
func (_c *PostCreateBulk) Save(ctx context.Context) ([]*Post, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Post, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PostCreateBulk) SaveX(ctx context.Context) []*Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
