// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PokeForum/PokeForum/ent/category"
	"github.com/PokeForum/PokeForum/ent/post"
	"github.com/PokeForum/PokeForum/ent/predicate"
	"github.com/PokeForum/PokeForum/ent/user"
)

// PostUpdate is the builder for updating Post entities.
type PostUpdate struct {
	config
	hooks    []Hook
	mutation *PostMutation
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdate) Where(ps ...predicate.Post) *PostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdate) SetUpdatedAt(v time.Time) *PostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PostUpdate) SetUserID(v int) *PostUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PostUpdate) SetNillableUserID(v *int) *PostUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *PostUpdate) SetCategoryID(v int) *PostUpdate {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *PostUpdate) SetNillableCategoryID(v *int) *PostUpdate {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PostUpdate) SetTitle(v string) *PostUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostUpdate) SetNillableTitle(v *string) *PostUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *PostUpdate) SetContent(v string) *PostUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PostUpdate) SetNillableContent(v *string) *PostUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetReadPermission sets the "read_permission" field.
func (_u *PostUpdate) SetReadPermission(v string) *PostUpdate {
	_u.mutation.SetReadPermission(v)
	return _u
}

// SetNillableReadPermission sets the "read_permission" field if the given value is not nil.
func (_u *PostUpdate) SetNillableReadPermission(v *string) *PostUpdate {
	if v != nil {
		_u.SetReadPermission(*v)
	}
	return _u
}

// ClearReadPermission clears the value of the "read_permission" field.
func (_u *PostUpdate) ClearReadPermission() *PostUpdate {
	_u.mutation.ClearReadPermission()
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *PostUpdate) SetViewCount(v int) *PostUpdate {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *PostUpdate) SetNillableViewCount(v *int) *PostUpdate {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *PostUpdate) AddViewCount(v int) *PostUpdate {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *PostUpdate) SetLikeCount(v int) *PostUpdate {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *PostUpdate) SetNillableLikeCount(v *int) *PostUpdate {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *PostUpdate) AddLikeCount(v int) *PostUpdate {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetDislikeCount sets the "dislike_count" field.
func (_u *PostUpdate) SetDislikeCount(v int) *PostUpdate {
	_u.mutation.ResetDislikeCount()
	_u.mutation.SetDislikeCount(v)
	return _u
}

// SetNillableDislikeCount sets the "dislike_count" field if the given value is not nil.
func (_u *PostUpdate) SetNillableDislikeCount(v *int) *PostUpdate {
	if v != nil {
		_u.SetDislikeCount(*v)
	}
	return _u
}

// AddDislikeCount adds value to the "dislike_count" field.
func (_u *PostUpdate) AddDislikeCount(v int) *PostUpdate {
	_u.mutation.AddDislikeCount(v)
	return _u
}

// SetFavoriteCount sets the "favorite_count" field.
func (_u *PostUpdate) SetFavoriteCount(v int) *PostUpdate {
	_u.mutation.ResetFavoriteCount()
	_u.mutation.SetFavoriteCount(v)
	return _u
}

// SetNillableFavoriteCount sets the "favorite_count" field if the given value is not nil.
func (_u *PostUpdate) SetNillableFavoriteCount(v *int) *PostUpdate {
	if v != nil {
		_u.SetFavoriteCount(*v)
	}
	return _u
}

// AddFavoriteCount adds value to the "favorite_count" field.
func (_u *PostUpdate) AddFavoriteCount(v int) *PostUpdate {
	_u.mutation.AddFavoriteCount(v)
	return _u
}

// SetIsEssence sets the "is_essence" field.
func (_u *PostUpdate) SetIsEssence(v bool) *PostUpdate {
	_u.mutation.SetIsEssence(v)
	return _u
}

// SetNillableIsEssence sets the "is_essence" field if the given value is not nil.
func (_u *PostUpdate) SetNillableIsEssence(v *bool) *PostUpdate {
	if v != nil {
		_u.SetIsEssence(*v)
	}
	return _u
}

// SetIsPinned sets the "is_pinned" field.
func (_u *PostUpdate) SetIsPinned(v bool) *PostUpdate {
	_u.mutation.SetIsPinned(v)
	return _u
}

// SetNillableIsPinned sets the "is_pinned" field if the given value is not nil.
func (_u *PostUpdate) SetNillableIsPinned(v *bool) *PostUpdate {
	if v != nil {
		_u.SetIsPinned(*v)
	}
	return _u
}

// SetPublishIP sets the "publish_ip" field.
func (_u *PostUpdate) SetPublishIP(v string) *PostUpdate {
	_u.mutation.SetPublishIP(v)
	return _u
}

// SetNillablePublishIP sets the "publish_ip" field if the given value is not nil.
func (_u *PostUpdate) SetNillablePublishIP(v *string) *PostUpdate {
	if v != nil {
		_u.SetPublishIP(*v)
	}
	return _u
}

// ClearPublishIP clears the value of the "publish_ip" field.
func (_u *PostUpdate) ClearPublishIP() *PostUpdate {
	_u.mutation.ClearPublishIP()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PostUpdate) SetStatus(v post.Status) *PostUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PostUpdate) SetNillableStatus(v *post.Status) *PostUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *PostUpdate) SetAuthorID(id int) *PostUpdate {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *PostUpdate) SetAuthor(v *User) *PostUpdate {
	return _u.SetAuthorID(v.ID)
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *PostUpdate) SetCategory(v *Category) *PostUpdate {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdate) Mutation() *PostMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *PostUpdate) ClearAuthor() *PostUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *PostUpdate) ClearCategory() *PostUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := post.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Post.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CategoryID(); ok {
		if err := post.CategoryIDValidator(v); err != nil {
			return &ValidationError{Name: "category_id", err: fmt.Errorf(`ent: validator failed for field "Post.category_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := post.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Post.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ViewCount(); ok {
		if err := post.ViewCountValidator(v); err != nil {
			return &ValidationError{Name: "view_count", err: fmt.Errorf(`ent: validator failed for field "Post.view_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LikeCount(); ok {
		if err := post.LikeCountValidator(v); err != nil {
			return &ValidationError{Name: "like_count", err: fmt.Errorf(`ent: validator failed for field "Post.like_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DislikeCount(); ok {
		if err := post.DislikeCountValidator(v); err != nil {
			return &ValidationError{Name: "dislike_count", err: fmt.Errorf(`ent: validator failed for field "Post.dislike_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FavoriteCount(); ok {
		if err := post.FavoriteCountValidator(v); err != nil {
			return &ValidationError{Name: "favorite_count", err: fmt.Errorf(`ent: validator failed for field "Post.favorite_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := post.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Post.status": %w`, err)}
		}
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.author"`)
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.category"`)
	}
	return nil
}

func (_u *PostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReadPermission(); ok {
		_spec.SetField(post.FieldReadPermission, field.TypeString, value)
	}
	if _u.mutation.ReadPermissionCleared() {
		_spec.ClearField(post.FieldReadPermission, field.TypeString)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(post.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(post.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(post.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(post.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DislikeCount(); ok {
		_spec.SetField(post.FieldDislikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDislikeCount(); ok {
		_spec.AddField(post.FieldDislikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FavoriteCount(); ok {
		_spec.SetField(post.FieldFavoriteCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFavoriteCount(); ok {
		_spec.AddField(post.FieldFavoriteCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsEssence(); ok {
		_spec.SetField(post.FieldIsEssence, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPinned(); ok {
		_spec.SetField(post.FieldIsPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PublishIP(); ok {
		_spec.SetField(post.FieldPublishIP, field.TypeString, value)
	}
	if _u.mutation.PublishIPCleared() {
		_spec.ClearField(post.FieldPublishIP, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(post.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.AuthorTable,
			Columns: []string{post.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.AuthorTable,
			Columns: []string{post.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.CategoryTable,
			Columns: []string{post.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.CategoryTable,
			Columns: []string{post.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostUpdateOne is the builder for updating a single Post entity.
type PostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdateOne) SetUpdatedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PostUpdateOne) SetUserID(v int) *PostUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableUserID(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *PostUpdateOne) SetCategoryID(v int) *PostUpdateOne {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableCategoryID(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PostUpdateOne) SetTitle(v string) *PostUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableTitle(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *PostUpdateOne) SetContent(v string) *PostUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableContent(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetReadPermission sets the "read_permission" field.
func (_u *PostUpdateOne) SetReadPermission(v string) *PostUpdateOne {
	_u.mutation.SetReadPermission(v)
	return _u
}

// SetNillableReadPermission sets the "read_permission" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableReadPermission(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetReadPermission(*v)
	}
	return _u
}

// ClearReadPermission clears the value of the "read_permission" field.
func (_u *PostUpdateOne) ClearReadPermission() *PostUpdateOne {
	_u.mutation.ClearReadPermission()
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *PostUpdateOne) SetViewCount(v int) *PostUpdateOne {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableViewCount(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *PostUpdateOne) AddViewCount(v int) *PostUpdateOne {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *PostUpdateOne) SetLikeCount(v int) *PostUpdateOne {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableLikeCount(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *PostUpdateOne) AddLikeCount(v int) *PostUpdateOne {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetDislikeCount sets the "dislike_count" field.
func (_u *PostUpdateOne) SetDislikeCount(v int) *PostUpdateOne {
	_u.mutation.ResetDislikeCount()
	_u.mutation.SetDislikeCount(v)
	return _u
}

// SetNillableDislikeCount sets the "dislike_count" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableDislikeCount(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetDislikeCount(*v)
	}
	return _u
}

// AddDislikeCount adds value to the "dislike_count" field.
func (_u *PostUpdateOne) AddDislikeCount(v int) *PostUpdateOne {
	_u.mutation.AddDislikeCount(v)
	return _u
}

// SetFavoriteCount sets the "favorite_count" field.
func (_u *PostUpdateOne) SetFavoriteCount(v int) *PostUpdateOne {
	_u.mutation.ResetFavoriteCount()
	_u.mutation.SetFavoriteCount(v)
	return _u
}

// SetNillableFavoriteCount sets the "favorite_count" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableFavoriteCount(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetFavoriteCount(*v)
	}
	return _u
}

// AddFavoriteCount adds value to the "favorite_count" field.
func (_u *PostUpdateOne) AddFavoriteCount(v int) *PostUpdateOne {
	_u.mutation.AddFavoriteCount(v)
	return _u
}

// SetIsEssence sets the "is_essence" field.
func (_u *PostUpdateOne) SetIsEssence(v bool) *PostUpdateOne {
	_u.mutation.SetIsEssence(v)
	return _u
}

// SetNillableIsEssence sets the "is_essence" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableIsEssence(v *bool) *PostUpdateOne {
	if v != nil {
		_u.SetIsEssence(*v)
	}
	return _u
}

// SetIsPinned sets the "is_pinned" field.
func (_u *PostUpdateOne) SetIsPinned(v bool) *PostUpdateOne {
	_u.mutation.SetIsPinned(v)
	return _u
}

// SetNillableIsPinned sets the "is_pinned" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableIsPinned(v *bool) *PostUpdateOne {
	if v != nil {
		_u.SetIsPinned(*v)
	}
	return _u
}

// SetPublishIP sets the "publish_ip" field.
func (_u *PostUpdateOne) SetPublishIP(v string) *PostUpdateOne {
	_u.mutation.SetPublishIP(v)
	return _u
}

// SetNillablePublishIP sets the "publish_ip" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillablePublishIP(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetPublishIP(*v)
	}
	return _u
}

// ClearPublishIP clears the value of the "publish_ip" field.
func (_u *PostUpdateOne) ClearPublishIP() *PostUpdateOne {
	_u.mutation.ClearPublishIP()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PostUpdateOne) SetStatus(v post.Status) *PostUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableStatus(v *post.Status) *PostUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *PostUpdateOne) SetAuthorID(id int) *PostUpdateOne {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *PostUpdateOne) SetAuthor(v *User) *PostUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *PostUpdateOne) SetCategory(v *Category) *PostUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdateOne) Mutation() *PostMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *PostUpdateOne) ClearAuthor() *PostUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *PostUpdateOne) ClearCategory() *PostUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdateOne) Where(ps ...predicate.Post) *PostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostUpdateOne) Select(field string, fields ...string) *PostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Post entity.
func (_u *PostUpdateOne) Save(ctx context.Context) (*Post, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdateOne) SaveX(ctx context.Context) *Post {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := post.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Post.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CategoryID(); ok {
		if err := post.CategoryIDValidator(v); err != nil {
			return &ValidationError{Name: "category_id", err: fmt.Errorf(`ent: validator failed for field "Post.category_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := post.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Post.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ViewCount(); ok {
		if err := post.ViewCountValidator(v); err != nil {
			return &ValidationError{Name: "view_count", err: fmt.Errorf(`ent: validator failed for field "Post.view_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LikeCount(); ok {
		if err := post.LikeCountValidator(v); err != nil {
			return &ValidationError{Name: "like_count", err: fmt.Errorf(`ent: validator failed for field "Post.like_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DislikeCount(); ok {
		if err := post.DislikeCountValidator(v); err != nil {
			return &ValidationError{Name: "dislike_count", err: fmt.Errorf(`ent: validator failed for field "Post.dislike_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FavoriteCount(); ok {
		if err := post.FavoriteCountValidator(v); err != nil {
			return &ValidationError{Name: "favorite_count", err: fmt.Errorf(`ent: validator failed for field "Post.favorite_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := post.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Post.status": %w`, err)}
		}
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.author"`)
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.category"`)
	}
	return nil
}

func (_u *PostUpdateOne) sqlSave(ctx context.Context) (_node *Post, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Post.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, post.FieldID)
		for _, f := range fields {
			if !post.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != post.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReadPermission(); ok {
		_spec.SetField(post.FieldReadPermission, field.TypeString, value)
	}
	if _u.mutation.ReadPermissionCleared() {
		_spec.ClearField(post.FieldReadPermission, field.TypeString)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(post.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(post.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(post.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(post.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DislikeCount(); ok {
		_spec.SetField(post.FieldDislikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDislikeCount(); ok {
		_spec.AddField(post.FieldDislikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FavoriteCount(); ok {
		_spec.SetField(post.FieldFavoriteCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFavoriteCount(); ok {
		_spec.AddField(post.FieldFavoriteCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsEssence(); ok {
		_spec.SetField(post.FieldIsEssence, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPinned(); ok {
		_spec.SetField(post.FieldIsPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PublishIP(); ok {
		_spec.SetField(post.FieldPublishIP, field.TypeString, value)
	}
	if _u.mutation.PublishIPCleared() {
		_spec.ClearField(post.FieldPublishIP, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(post.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.AuthorTable,
			Columns: []string{post.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.AuthorTable,
			Columns: []string{post.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.CategoryTable,
			Columns: []string{post.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.CategoryTable,
			Columns: []string{post.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Post{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
