// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PokeForum/PokeForum/ent/predicate"
	"github.com/PokeForum/PokeForum/ent/report"
	"github.com/PokeForum/PokeForum/ent/schema"
)

// ReportUpdate is the builder for updating Report entities.
type ReportUpdate struct {
	config
	hooks    []Hook
	mutation *ReportMutation
}

// Where appends a list predicates to the ReportUpdate builder.
func (_u *ReportUpdate) Where(ps ...predicate.Report) *ReportUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReportUpdate) SetUpdatedAt(v time.Time) *ReportUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetReporterID sets the "reporter_id" field.
func (_u *ReportUpdate) SetReporterID(v int) *ReportUpdate {
	_u.mutation.ResetReporterID()
	_u.mutation.SetReporterID(v)
	return _u
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableReporterID(v *int) *ReportUpdate {
	if v != nil {
		_u.SetReporterID(*v)
	}
	return _u
}

// AddReporterID adds value to the "reporter_id" field.
func (_u *ReportUpdate) AddReporterID(v int) *ReportUpdate {
	_u.mutation.AddReporterID(v)
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *ReportUpdate) SetTargetID(v int) *ReportUpdate {
	_u.mutation.ResetTargetID()
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableTargetID(v *int) *ReportUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// AddTargetID adds value to the "target_id" field.
func (_u *ReportUpdate) AddTargetID(v int) *ReportUpdate {
	_u.mutation.AddTargetID(v)
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *ReportUpdate) SetTargetType(v schema.ReportTargetType) *ReportUpdate {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableTargetType(v *schema.ReportTargetType) *ReportUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetAuthorID sets the "target_author_id" field.
func (_u *ReportUpdate) SetTargetAuthorID(v int) *ReportUpdate {
	_u.mutation.ResetTargetAuthorID()
	_u.mutation.SetTargetAuthorID(v)
	return _u
}

// SetNillableTargetAuthorID sets the "target_author_id" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableTargetAuthorID(v *int) *ReportUpdate {
	if v != nil {
		_u.SetTargetAuthorID(*v)
	}
	return _u
}

// AddTargetAuthorID adds value to the "target_author_id" field.
func (_u *ReportUpdate) AddTargetAuthorID(v int) *ReportUpdate {
	_u.mutation.AddTargetAuthorID(v)
	return _u
}

// SetReportType sets the "report_type" field.
func (_u *ReportUpdate) SetReportType(v schema.ReportType) *ReportUpdate {
	_u.mutation.SetReportType(v)
	return _u
}

// SetNillableReportType sets the "report_type" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableReportType(v *schema.ReportType) *ReportUpdate {
	if v != nil {
		_u.SetReportType(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *ReportUpdate) SetReason(v string) *ReportUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableReason(v *string) *ReportUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *ReportUpdate) ClearReason() *ReportUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReportUpdate) SetStatus(v schema.ReportStatus) *ReportUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableStatus(v *schema.ReportStatus) *ReportUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHandlerID sets the "handler_id" field.
func (_u *ReportUpdate) SetHandlerID(v int) *ReportUpdate {
	_u.mutation.ResetHandlerID()
	_u.mutation.SetHandlerID(v)
	return _u
}

// SetNillableHandlerID sets the "handler_id" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableHandlerID(v *int) *ReportUpdate {
	if v != nil {
		_u.SetHandlerID(*v)
	}
	return _u
}

// AddHandlerID adds value to the "handler_id" field.
func (_u *ReportUpdate) AddHandlerID(v int) *ReportUpdate {
	_u.mutation.AddHandlerID(v)
	return _u
}

// ClearHandlerID clears the value of the "handler_id" field.
func (_u *ReportUpdate) ClearHandlerID() *ReportUpdate {
	_u.mutation.ClearHandlerID()
	return _u
}

// SetHandleResult sets the "handle_result" field.
func (_u *ReportUpdate) SetHandleResult(v string) *ReportUpdate {
	_u.mutation.SetHandleResult(v)
	return _u
}

// SetNillableHandleResult sets the "handle_result" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableHandleResult(v *string) *ReportUpdate {
	if v != nil {
		_u.SetHandleResult(*v)
	}
	return _u
}

// ClearHandleResult clears the value of the "handle_result" field.
func (_u *ReportUpdate) ClearHandleResult() *ReportUpdate {
	_u.mutation.ClearHandleResult()
	return _u
}

// SetHandleAction sets the "handle_action" field.
func (_u *ReportUpdate) SetHandleAction(v string) *ReportUpdate {
	_u.mutation.SetHandleAction(v)
	return _u
}

// SetNillableHandleAction sets the "handle_action" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableHandleAction(v *string) *ReportUpdate {
	if v != nil {
		_u.SetHandleAction(*v)
	}
	return _u
}

// ClearHandleAction clears the value of the "handle_action" field.
func (_u *ReportUpdate) ClearHandleAction() *ReportUpdate {
	_u.mutation.ClearHandleAction()
	return _u
}

// SetHandledAt sets the "handled_at" field.
func (_u *ReportUpdate) SetHandledAt(v time.Time) *ReportUpdate {
	_u.mutation.SetHandledAt(v)
	return _u
}

// SetNillableHandledAt sets the "handled_at" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableHandledAt(v *time.Time) *ReportUpdate {
	if v != nil {
		_u.SetHandledAt(*v)
	}
	return _u
}

// ClearHandledAt clears the value of the "handled_at" field.
func (_u *ReportUpdate) ClearHandledAt() *ReportUpdate {
	_u.mutation.ClearHandledAt()
	return _u
}

// Mutation returns the ReportMutation object of the builder.
func (_u *ReportUpdate) Mutation() *ReportMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReportUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReportUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReportUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReportUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReportUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := report.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReportUpdate) check() error {
	if v, ok := _u.mutation.ReporterID(); ok {
		if err := report.ReporterIDValidator(v); err != nil {
			return &ValidationError{Name: "reporter_id", err: fmt.Errorf(`ent: validator failed for field "Report.reporter_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetID(); ok {
		if err := report.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`ent: validator failed for field "Report.target_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetAuthorID(); ok {
		if err := report.TargetAuthorIDValidator(v); err != nil {
			return &ValidationError{Name: "target_author_id", err: fmt.Errorf(`ent: validator failed for field "Report.target_author_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := report.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "Report.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HandlerID(); ok {
		if err := report.HandlerIDValidator(v); err != nil {
			return &ValidationError{Name: "handler_id", err: fmt.Errorf(`ent: validator failed for field "Report.handler_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HandleResult(); ok {
		if err := report.HandleResultValidator(v); err != nil {
			return &ValidationError{Name: "handle_result", err: fmt.Errorf(`ent: validator failed for field "Report.handle_result": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HandleAction(); ok {
		if err := report.HandleActionValidator(v); err != nil {
			return &ValidationError{Name: "handle_action", err: fmt.Errorf(`ent: validator failed for field "Report.handle_action": %w`, err)}
		}
	}
	return nil
}

func (_u *ReportUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(report.Table, report.Columns, sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(report.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReporterID(); ok {
		_spec.SetField(report.FieldReporterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReporterID(); ok {
		_spec.AddField(report.FieldReporterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(report.FieldTargetID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetID(); ok {
		_spec.AddField(report.FieldTargetID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(report.FieldTargetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetAuthorID(); ok {
		_spec.SetField(report.FieldTargetAuthorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetAuthorID(); ok {
		_spec.AddField(report.FieldTargetAuthorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReportType(); ok {
		_spec.SetField(report.FieldReportType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(report.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(report.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.HandlerID(); ok {
		_spec.SetField(report.FieldHandlerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHandlerID(); ok {
		_spec.AddField(report.FieldHandlerID, field.TypeInt, value)
	}
	if _u.mutation.HandlerIDCleared() {
		_spec.ClearField(report.FieldHandlerID, field.TypeInt)
	}
	if value, ok := _u.mutation.HandleResult(); ok {
		_spec.SetField(report.FieldHandleResult, field.TypeString, value)
	}
	if _u.mutation.HandleResultCleared() {
		_spec.ClearField(report.FieldHandleResult, field.TypeString)
	}
	if value, ok := _u.mutation.HandleAction(); ok {
		_spec.SetField(report.FieldHandleAction, field.TypeString, value)
	}
	if _u.mutation.HandleActionCleared() {
		_spec.ClearField(report.FieldHandleAction, field.TypeString)
	}
	if value, ok := _u.mutation.HandledAt(); ok {
		_spec.SetField(report.FieldHandledAt, field.TypeTime, value)
	}
	if _u.mutation.HandledAtCleared() {
		_spec.ClearField(report.FieldHandledAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{report.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReportUpdateOne is the builder for updating a single Report entity.
type ReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReportMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReportUpdateOne) SetUpdatedAt(v time.Time) *ReportUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetReporterID sets the "reporter_id" field.
func (_u *ReportUpdateOne) SetReporterID(v int) *ReportUpdateOne {
	_u.mutation.ResetReporterID()
	_u.mutation.SetReporterID(v)
	return _u
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableReporterID(v *int) *ReportUpdateOne {
	if v != nil {
		_u.SetReporterID(*v)
	}
	return _u
}

// AddReporterID adds value to the "reporter_id" field.
func (_u *ReportUpdateOne) AddReporterID(v int) *ReportUpdateOne {
	_u.mutation.AddReporterID(v)
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *ReportUpdateOne) SetTargetID(v int) *ReportUpdateOne {
	_u.mutation.ResetTargetID()
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableTargetID(v *int) *ReportUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// AddTargetID adds value to the "target_id" field.
func (_u *ReportUpdateOne) AddTargetID(v int) *ReportUpdateOne {
	_u.mutation.AddTargetID(v)
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *ReportUpdateOne) SetTargetType(v schema.ReportTargetType) *ReportUpdateOne {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableTargetType(v *schema.ReportTargetType) *ReportUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetAuthorID sets the "target_author_id" field.
func (_u *ReportUpdateOne) SetTargetAuthorID(v int) *ReportUpdateOne {
	_u.mutation.ResetTargetAuthorID()
	_u.mutation.SetTargetAuthorID(v)
	return _u
}

// SetNillableTargetAuthorID sets the "target_author_id" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableTargetAuthorID(v *int) *ReportUpdateOne {
	if v != nil {
		_u.SetTargetAuthorID(*v)
	}
	return _u
}

// AddTargetAuthorID adds value to the "target_author_id" field.
func (_u *ReportUpdateOne) AddTargetAuthorID(v int) *ReportUpdateOne {
	_u.mutation.AddTargetAuthorID(v)
	return _u
}

// SetReportType sets the "report_type" field.
func (_u *ReportUpdateOne) SetReportType(v schema.ReportType) *ReportUpdateOne {
	_u.mutation.SetReportType(v)
	return _u
}

// SetNillableReportType sets the "report_type" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableReportType(v *schema.ReportType) *ReportUpdateOne {
	if v != nil {
		_u.SetReportType(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *ReportUpdateOne) SetReason(v string) *ReportUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableReason(v *string) *ReportUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *ReportUpdateOne) ClearReason() *ReportUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReportUpdateOne) SetStatus(v schema.ReportStatus) *ReportUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableStatus(v *schema.ReportStatus) *ReportUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHandlerID sets the "handler_id" field.
func (_u *ReportUpdateOne) SetHandlerID(v int) *ReportUpdateOne {
	_u.mutation.ResetHandlerID()
	_u.mutation.SetHandlerID(v)
	return _u
}

// SetNillableHandlerID sets the "handler_id" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableHandlerID(v *int) *ReportUpdateOne {
	if v != nil {
		_u.SetHandlerID(*v)
	}
	return _u
}

// AddHandlerID adds value to the "handler_id" field.
func (_u *ReportUpdateOne) AddHandlerID(v int) *ReportUpdateOne {
	_u.mutation.AddHandlerID(v)
	return _u
}

// ClearHandlerID clears the value of the "handler_id" field.
func (_u *ReportUpdateOne) ClearHandlerID() *ReportUpdateOne {
	_u.mutation.ClearHandlerID()
	return _u
}

// SetHandleResult sets the "handle_result" field.
func (_u *ReportUpdateOne) SetHandleResult(v string) *ReportUpdateOne {
	_u.mutation.SetHandleResult(v)
	return _u
}

// SetNillableHandleResult sets the "handle_result" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableHandleResult(v *string) *ReportUpdateOne {
	if v != nil {
		_u.SetHandleResult(*v)
	}
	return _u
}

// ClearHandleResult clears the value of the "handle_result" field.
func (_u *ReportUpdateOne) ClearHandleResult() *ReportUpdateOne {
	_u.mutation.ClearHandleResult()
	return _u
}

// SetHandleAction sets the "handle_action" field.
func (_u *ReportUpdateOne) SetHandleAction(v string) *ReportUpdateOne {
	_u.mutation.SetHandleAction(v)
	return _u
}

// SetNillableHandleAction sets the "handle_action" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableHandleAction(v *string) *ReportUpdateOne {
	if v != nil {
		_u.SetHandleAction(*v)
	}
	return _u
}

// ClearHandleAction clears the value of the "handle_action" field.
func (_u *ReportUpdateOne) ClearHandleAction() *ReportUpdateOne {
	_u.mutation.ClearHandleAction()
	return _u
}

// SetHandledAt sets the "handled_at" field.
func (_u *ReportUpdateOne) SetHandledAt(v time.Time) *ReportUpdateOne {
	_u.mutation.SetHandledAt(v)
	return _u
}

// SetNillableHandledAt sets the "handled_at" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableHandledAt(v *time.Time) *ReportUpdateOne {
	if v != nil {
		_u.SetHandledAt(*v)
	}
	return _u
}

// ClearHandledAt clears the value of the "handled_at" field.
func (_u *ReportUpdateOne) ClearHandledAt() *ReportUpdateOne {
	_u.mutation.ClearHandledAt()
	return _u
}

// Mutation returns the ReportMutation object of the builder.
func (_u *ReportUpdateOne) Mutation() *ReportMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReportUpdate builder.
func (_u *ReportUpdateOne) Where(ps ...predicate.Report) *ReportUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReportUpdateOne) Select(field string, fields ...string) *ReportUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Report entity.
func (_u *ReportUpdateOne) Save(ctx context.Context) (*Report, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReportUpdateOne) SaveX(ctx context.Context) *Report {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReportUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReportUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReportUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := report.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReportUpdateOne) check() error {
	if v, ok := _u.mutation.ReporterID(); ok {
		if err := report.ReporterIDValidator(v); err != nil {
			return &ValidationError{Name: "reporter_id", err: fmt.Errorf(`ent: validator failed for field "Report.reporter_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetID(); ok {
		if err := report.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`ent: validator failed for field "Report.target_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetAuthorID(); ok {
		if err := report.TargetAuthorIDValidator(v); err != nil {
			return &ValidationError{Name: "target_author_id", err: fmt.Errorf(`ent: validator failed for field "Report.target_author_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := report.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "Report.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HandlerID(); ok {
		if err := report.HandlerIDValidator(v); err != nil {
			return &ValidationError{Name: "handler_id", err: fmt.Errorf(`ent: validator failed for field "Report.handler_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HandleResult(); ok {
		if err := report.HandleResultValidator(v); err != nil {
			return &ValidationError{Name: "handle_result", err: fmt.Errorf(`ent: validator failed for field "Report.handle_result": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HandleAction(); ok {
		if err := report.HandleActionValidator(v); err != nil {
			return &ValidationError{Name: "handle_action", err: fmt.Errorf(`ent: validator failed for field "Report.handle_action": %w`, err)}
		}
	}
	return nil
}

func (_u *ReportUpdateOne) sqlSave(ctx context.Context) (_node *Report, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(report.Table, report.Columns, sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Report.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, report.FieldID)
		for _, f := range fields {
			if !report.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != report.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(report.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReporterID(); ok {
		_spec.SetField(report.FieldReporterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReporterID(); ok {
		_spec.AddField(report.FieldReporterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(report.FieldTargetID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetID(); ok {
		_spec.AddField(report.FieldTargetID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(report.FieldTargetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetAuthorID(); ok {
		_spec.SetField(report.FieldTargetAuthorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetAuthorID(); ok {
		_spec.AddField(report.FieldTargetAuthorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReportType(); ok {
		_spec.SetField(report.FieldReportType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(report.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(report.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.HandlerID(); ok {
		_spec.SetField(report.FieldHandlerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHandlerID(); ok {
		_spec.AddField(report.FieldHandlerID, field.TypeInt, value)
	}
	if _u.mutation.HandlerIDCleared() {
		_spec.ClearField(report.FieldHandlerID, field.TypeInt)
	}
	if value, ok := _u.mutation.HandleResult(); ok {
		_spec.SetField(report.FieldHandleResult, field.TypeString, value)
	}
	if _u.mutation.HandleResultCleared() {
		_spec.ClearField(report.FieldHandleResult, field.TypeString)
	}
	if value, ok := _u.mutation.HandleAction(); ok {
		_spec.SetField(report.FieldHandleAction, field.TypeString, value)
	}
	if _u.mutation.HandleActionCleared() {
		_spec.ClearField(report.FieldHandleAction, field.TypeString)
	}
	if value, ok := _u.mutation.HandledAt(); ok {
		_spec.SetField(report.FieldHandledAt, field.TypeTime, value)
	}
	if _u.mutation.HandledAtCleared() {
		_spec.ClearField(report.FieldHandledAt, field.TypeTime)
	}
	_node = &Report{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{report.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
