// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PokeForum/PokeForum/ent/report"
	"github.com/PokeForum/PokeForum/ent/schema"
)

// ReportCreate is the builder for creating a Report entity.
type ReportCreate struct {
	config
	mutation *ReportMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReportCreate) SetCreatedAt(v time.Time) *ReportCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReportCreate) SetNillableCreatedAt(v *time.Time) *ReportCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReportCreate) SetUpdatedAt(v time.Time) *ReportCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReportCreate) SetNillableUpdatedAt(v *time.Time) *ReportCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetReporterID sets the "reporter_id" field.
func (_c *ReportCreate) SetReporterID(v int) *ReportCreate {
	_c.mutation.SetReporterID(v)
	return _c
}

// SetTargetID sets the "target_id" field.
func (_c *ReportCreate) SetTargetID(v int) *ReportCreate {
	_c.mutation.SetTargetID(v)
	return _c
}

// SetTargetType sets the "target_type" field.
func (_c *ReportCreate) SetTargetType(v schema.ReportTargetType) *ReportCreate {
	_c.mutation.SetTargetType(v)
	return _c
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_c *ReportCreate) SetNillableTargetType(v *schema.ReportTargetType) *ReportCreate {
	if v != nil {
		_c.SetTargetType(*v)
	}
	return _c
}

// SetTargetAuthorID sets the "target_author_id" field.
func (_c *ReportCreate) SetTargetAuthorID(v int) *ReportCreate {
	_c.mutation.SetTargetAuthorID(v)
	return _c
}

// SetReportType sets the "report_type" field.
func (_c *ReportCreate) SetReportType(v schema.ReportType) *ReportCreate {
	_c.mutation.SetReportType(v)
	return _c
}

// SetNillableReportType sets the "report_type" field if the given value is not nil.
func (_c *ReportCreate) SetNillableReportType(v *schema.ReportType) *ReportCreate {
	if v != nil {
		_c.SetReportType(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *ReportCreate) SetReason(v string) *ReportCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *ReportCreate) SetNillableReason(v *string) *ReportCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReportCreate) SetStatus(v schema.ReportStatus) *ReportCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ReportCreate) SetNillableStatus(v *schema.ReportStatus) *ReportCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetHandlerID sets the "handler_id" field.
func (_c *ReportCreate) SetHandlerID(v int) *ReportCreate {
	_c.mutation.SetHandlerID(v)
	return _c
}

// SetNillableHandlerID sets the "handler_id" field if the given value is not nil.
func (_c *ReportCreate) SetNillableHandlerID(v *int) *ReportCreate {
	if v != nil {
		_c.SetHandlerID(*v)
	}
	return _c
}

// SetHandleResult sets the "handle_result" field.
func (_c *ReportCreate) SetHandleResult(v string) *ReportCreate {
	_c.mutation.SetHandleResult(v)
	return _c
}

// SetNillableHandleResult sets the "handle_result" field if the given value is not nil.
func (_c *ReportCreate) SetNillableHandleResult(v *string) *ReportCreate {
	if v != nil {
		_c.SetHandleResult(*v)
	}
	return _c
}

// SetHandleAction sets the "handle_action" field.
func (_c *ReportCreate) SetHandleAction(v string) *ReportCreate {
	_c.mutation.SetHandleAction(v)
	return _c
}

// SetNillableHandleAction sets the "handle_action" field if the given value is not nil.
func (_c *ReportCreate) SetNillableHandleAction(v *string) *ReportCreate {
	if v != nil {
		_c.SetHandleAction(*v)
	}
	return _c
}

// SetHandledAt sets the "handled_at" field.
func (_c *ReportCreate) SetHandledAt(v time.Time) *ReportCreate {
	_c.mutation.SetHandledAt(v)
	return _c
}

// SetNillableHandledAt sets the "handled_at" field if the given value is not nil.
func (_c *ReportCreate) SetNillableHandledAt(v *time.Time) *ReportCreate {
	if v != nil {
		_c.SetHandledAt(*v)
	}
	return _c
}

// Mutation returns the ReportMutation object of the builder.
func (_c *ReportCreate) Mutation() *ReportMutation {
	return _c.mutation
}

// Save creates the Report in the database.
func (_c *ReportCreate) Save(ctx context.Context) (*Report, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReportCreate) SaveX(ctx context.Context) *Report {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReportCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := report.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := report.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TargetType(); !ok {
		v := report.DefaultTargetType
		_c.mutation.SetTargetType(v)
	}
	if _, ok := _c.mutation.ReportType(); !ok {
		v := report.DefaultReportType
		_c.mutation.SetReportType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := report.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReportCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Report.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Report.updated_at"`)}
	}
	if _, ok := _c.mutation.ReporterID(); !ok {
		return &ValidationError{Name: "reporter_id", err: errors.New(`ent: missing required field "Report.reporter_id"`)}
	}
	if v, ok := _c.mutation.ReporterID(); ok {
		if err := report.ReporterIDValidator(v); err != nil {
			return &ValidationError{Name: "reporter_id", err: fmt.Errorf(`ent: validator failed for field "Report.reporter_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetID(); !ok {
		return &ValidationError{Name: "target_id", err: errors.New(`ent: missing required field "Report.target_id"`)}
	}
	if v, ok := _c.mutation.TargetID(); ok {
		if err := report.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`ent: validator failed for field "Report.target_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetType(); !ok {
		return &ValidationError{Name: "target_type", err: errors.New(`ent: missing required field "Report.target_type"`)}
	}
	if _, ok := _c.mutation.TargetAuthorID(); !ok {
		return &ValidationError{Name: "target_author_id", err: errors.New(`ent: missing required field "Report.target_author_id"`)}
	}
	if v, ok := _c.mutation.TargetAuthorID(); ok {
		if err := report.TargetAuthorIDValidator(v); err != nil {
			return &ValidationError{Name: "target_author_id", err: fmt.Errorf(`ent: validator failed for field "Report.target_author_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReportType(); !ok {
		return &ValidationError{Name: "report_type", err: errors.New(`ent: missing required field "Report.report_type"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := report.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "Report.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Report.status"`)}
	}
	if v, ok := _c.mutation.HandlerID(); ok {
		if err := report.HandlerIDValidator(v); err != nil {
			return &ValidationError{Name: "handler_id", err: fmt.Errorf(`ent: validator failed for field "Report.handler_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.HandleResult(); ok {
		if err := report.HandleResultValidator(v); err != nil {
			return &ValidationError{Name: "handle_result", err: fmt.Errorf(`ent: validator failed for field "Report.handle_result": %w`, err)}
		}
	}
	if v, ok := _c.mutation.HandleAction(); ok {
		if err := report.HandleActionValidator(v); err != nil {
			return &ValidationError{Name: "handle_action", err: fmt.Errorf(`ent: validator failed for field "Report.handle_action": %w`, err)}
		}
	}
	return nil
}

func (_c *ReportCreate) sqlSave(ctx context.Context) (*Report, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReportCreate) createSpec() (*Report, *sqlgraph.CreateSpec) {
	var (
		_node = &Report{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(report.Table, sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(report.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(report.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ReporterID(); ok {
		_spec.SetField(report.FieldReporterID, field.TypeInt, value)
		_node.ReporterID = value
	}
	if value, ok := _c.mutation.TargetID(); ok {
		_spec.SetField(report.FieldTargetID, field.TypeInt, value)
		_node.TargetID = value
	}
	if value, ok := _c.mutation.TargetType(); ok {
		_spec.SetField(report.FieldTargetType, field.TypeString, value)
		_node.TargetType = value
	}
	if value, ok := _c.mutation.TargetAuthorID(); ok {
		_spec.SetField(report.FieldTargetAuthorID, field.TypeInt, value)
		_node.TargetAuthorID = value
	}
	if value, ok := _c.mutation.ReportType(); ok {
		_spec.SetField(report.FieldReportType, field.TypeString, value)
		_node.ReportType = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(report.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.HandlerID(); ok {
		_spec.SetField(report.FieldHandlerID, field.TypeInt, value)
		_node.HandlerID = &value
	}
	if value, ok := _c.mutation.HandleResult(); ok {
		_spec.SetField(report.FieldHandleResult, field.TypeString, value)
		_node.HandleResult = value
	}
	if value, ok := _c.mutation.HandleAction(); ok {
		_spec.SetField(report.FieldHandleAction, field.TypeString, value)
		_node.HandleAction = value
	}
	if value, ok := _c.mutation.HandledAt(); ok {
		_spec.SetField(report.FieldHandledAt, field.TypeTime, value)
		_node.HandledAt = &value
	}
	return _node, _spec
}

// ReportCreateBulk is the builder for creating many Report entities in bulk.
type ReportCreateBulk struct {
	config
	err      error
	builders []*ReportCreate
}

// Save creates the Report entities in the database.
func (_c *ReportCreateBulk) Save(ctx context.Context) ([]*Report, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Report, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReportCreateBulk) SaveX(ctx context.Context) []*Report {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
