// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/PokeForum/PokeForum/ent/category"
	"github.com/PokeForum/PokeForum/ent/comment"
	"github.com/PokeForum/PokeForum/ent/commentaction"
	"github.com/PokeForum/PokeForum/ent/post"
	"github.com/PokeForum/PokeForum/ent/postaction"
	"github.com/PokeForum/PokeForum/ent/schema"
	"github.com/PokeForum/PokeForum/ent/user"
	"github.com/PokeForum/PokeForum/ent/userloginlog"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryMixin := schema.Category{}.Mixin()
	categoryMixinFields0 := categoryMixin[0].Fields()
	_ = categoryMixinFields0
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryMixinFields0[0].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryMixinFields0[1].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[1].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescSlug is the schema descriptor for slug field.
	categoryDescSlug := categoryFields[2].Descriptor()
	// category.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	category.SlugValidator = categoryDescSlug.Validators[0].(func(string) error)
	// categoryDescWeight is the schema descriptor for weight field.
	categoryDescWeight := categoryFields[5].Descriptor()
	// category.DefaultWeight holds the default value on creation for the weight field.
	category.DefaultWeight = categoryDescWeight.Default.(int)
	// categoryDescID is the schema descriptor for id field.
	categoryDescID := categoryFields[0].Descriptor()
	// category.IDValidator is a validator for the "id" field. It is called by the builders before save.
	category.IDValidator = categoryDescID.Validators[0].(func(int) error)
	commentMixin := schema.Comment{}.Mixin()
	commentMixinFields0 := commentMixin[0].Fields()
	_ = commentMixinFields0
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentMixinFields0[0].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescUpdatedAt is the schema descriptor for updated_at field.
	commentDescUpdatedAt := commentMixinFields0[1].Descriptor()
	// comment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comment.DefaultUpdatedAt = commentDescUpdatedAt.Default.(func() time.Time)
	// comment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comment.UpdateDefaultUpdatedAt = commentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// commentDescPostID is the schema descriptor for post_id field.
	commentDescPostID := commentFields[1].Descriptor()
	// comment.PostIDValidator is a validator for the "post_id" field. It is called by the builders before save.
	comment.PostIDValidator = commentDescPostID.Validators[0].(func(int) error)
	// commentDescUserID is the schema descriptor for user_id field.
	commentDescUserID := commentFields[2].Descriptor()
	// comment.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	comment.UserIDValidator = commentDescUserID.Validators[0].(func(int) error)
	// commentDescContent is the schema descriptor for content field.
	commentDescContent := commentFields[5].Descriptor()
	// comment.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	comment.ContentValidator = commentDescContent.Validators[0].(func(string) error)
	// commentDescLikeCount is the schema descriptor for like_count field.
	commentDescLikeCount := commentFields[6].Descriptor()
	// comment.DefaultLikeCount holds the default value on creation for the like_count field.
	comment.DefaultLikeCount = commentDescLikeCount.Default.(int)
	// comment.LikeCountValidator is a validator for the "like_count" field. It is called by the builders before save.
	comment.LikeCountValidator = commentDescLikeCount.Validators[0].(func(int) error)
	// commentDescDislikeCount is the schema descriptor for dislike_count field.
	commentDescDislikeCount := commentFields[7].Descriptor()
	// comment.DefaultDislikeCount holds the default value on creation for the dislike_count field.
	comment.DefaultDislikeCount = commentDescDislikeCount.Default.(int)
	// comment.DislikeCountValidator is a validator for the "dislike_count" field. It is called by the builders before save.
	comment.DislikeCountValidator = commentDescDislikeCount.Validators[0].(func(int) error)
	// commentDescIsSelected is the schema descriptor for is_selected field.
	commentDescIsSelected := commentFields[8].Descriptor()
	// comment.DefaultIsSelected holds the default value on creation for the is_selected field.
	comment.DefaultIsSelected = commentDescIsSelected.Default.(bool)
	// commentDescIsPinned is the schema descriptor for is_pinned field.
	commentDescIsPinned := commentFields[9].Descriptor()
	// comment.DefaultIsPinned holds the default value on creation for the is_pinned field.
	comment.DefaultIsPinned = commentDescIsPinned.Default.(bool)
	// commentDescID is the schema descriptor for id field.
	commentDescID := commentFields[0].Descriptor()
	// comment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	comment.IDValidator = commentDescID.Validators[0].(func(int) error)
	commentactionMixin := schema.CommentAction{}.Mixin()
	commentactionMixinFields0 := commentactionMixin[0].Fields()
	_ = commentactionMixinFields0
	commentactionFields := schema.CommentAction{}.Fields()
	_ = commentactionFields
	// commentactionDescCreatedAt is the schema descriptor for created_at field.
	commentactionDescCreatedAt := commentactionMixinFields0[0].Descriptor()
	// commentaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	commentaction.DefaultCreatedAt = commentactionDescCreatedAt.Default.(func() time.Time)
	// commentactionDescUpdatedAt is the schema descriptor for updated_at field.
	commentactionDescUpdatedAt := commentactionMixinFields0[1].Descriptor()
	// commentaction.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	commentaction.DefaultUpdatedAt = commentactionDescUpdatedAt.Default.(func() time.Time)
	// commentaction.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	commentaction.UpdateDefaultUpdatedAt = commentactionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// commentactionDescUserID is the schema descriptor for user_id field.
	commentactionDescUserID := commentactionFields[1].Descriptor()
	// commentaction.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	commentaction.UserIDValidator = commentactionDescUserID.Validators[0].(func(int) error)
	// commentactionDescCommentID is the schema descriptor for comment_id field.
	commentactionDescCommentID := commentactionFields[2].Descriptor()
	// commentaction.CommentIDValidator is a validator for the "comment_id" field. It is called by the builders before save.
	commentaction.CommentIDValidator = commentactionDescCommentID.Validators[0].(func(int) error)
	// commentactionDescID is the schema descriptor for id field.
	commentactionDescID := commentactionFields[0].Descriptor()
	// commentaction.IDValidator is a validator for the "id" field. It is called by the builders before save.
	commentaction.IDValidator = commentactionDescID.Validators[0].(func(int) error)
	postMixin := schema.Post{}.Mixin()
	postMixinFields0 := postMixin[0].Fields()
	_ = postMixinFields0
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescCreatedAt is the schema descriptor for created_at field.
	postDescCreatedAt := postMixinFields0[0].Descriptor()
	// post.DefaultCreatedAt holds the default value on creation for the created_at field.
	post.DefaultCreatedAt = postDescCreatedAt.Default.(func() time.Time)
	// postDescUpdatedAt is the schema descriptor for updated_at field.
	postDescUpdatedAt := postMixinFields0[1].Descriptor()
	// post.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	post.DefaultUpdatedAt = postDescUpdatedAt.Default.(func() time.Time)
	// post.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	post.UpdateDefaultUpdatedAt = postDescUpdatedAt.UpdateDefault.(func() time.Time)
	// postDescUserID is the schema descriptor for user_id field.
	postDescUserID := postFields[1].Descriptor()
	// post.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	post.UserIDValidator = postDescUserID.Validators[0].(func(int) error)
	// postDescCategoryID is the schema descriptor for category_id field.
	postDescCategoryID := postFields[2].Descriptor()
	// post.CategoryIDValidator is a validator for the "category_id" field. It is called by the builders before save.
	post.CategoryIDValidator = postDescCategoryID.Validators[0].(func(int) error)
	// postDescTitle is the schema descriptor for title field.
	postDescTitle := postFields[3].Descriptor()
	// post.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	post.TitleValidator = postDescTitle.Validators[0].(func(string) error)
	// postDescContent is the schema descriptor for content field.
	postDescContent := postFields[4].Descriptor()
	// post.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	post.ContentValidator = postDescContent.Validators[0].(func(string) error)
	// postDescViewCount is the schema descriptor for view_count field.
	postDescViewCount := postFields[6].Descriptor()
	// post.DefaultViewCount holds the default value on creation for the view_count field.
	post.DefaultViewCount = postDescViewCount.Default.(int)
	// post.ViewCountValidator is a validator for the "view_count" field. It is called by the builders before save.
	post.ViewCountValidator = postDescViewCount.Validators[0].(func(int) error)
	// postDescLikeCount is the schema descriptor for like_count field.
	postDescLikeCount := postFields[7].Descriptor()
	// post.DefaultLikeCount holds the default value on creation for the like_count field.
	post.DefaultLikeCount = postDescLikeCount.Default.(int)
	// post.LikeCountValidator is a validator for the "like_count" field. It is called by the builders before save.
	post.LikeCountValidator = postDescLikeCount.Validators[0].(func(int) error)
	// postDescDislikeCount is the schema descriptor for dislike_count field.
	postDescDislikeCount := postFields[8].Descriptor()
	// post.DefaultDislikeCount holds the default value on creation for the dislike_count field.
	post.DefaultDislikeCount = postDescDislikeCount.Default.(int)
	// post.DislikeCountValidator is a validator for the "dislike_count" field. It is called by the builders before save.
	post.DislikeCountValidator = postDescDislikeCount.Validators[0].(func(int) error)
	// postDescFavoriteCount is the schema descriptor for favorite_count field.
	postDescFavoriteCount := postFields[9].Descriptor()
	// post.DefaultFavoriteCount holds the default value on creation for the favorite_count field.
	post.DefaultFavoriteCount = postDescFavoriteCount.Default.(int)
	// post.FavoriteCountValidator is a validator for the "favorite_count" field. It is called by the builders before save.
	post.FavoriteCountValidator = postDescFavoriteCount.Validators[0].(func(int) error)
	// postDescIsEssence is the schema descriptor for is_essence field.
	postDescIsEssence := postFields[10].Descriptor()
	// post.DefaultIsEssence holds the default value on creation for the is_essence field.
	post.DefaultIsEssence = postDescIsEssence.Default.(bool)
	// postDescIsPinned is the schema descriptor for is_pinned field.
	postDescIsPinned := postFields[11].Descriptor()
	// post.DefaultIsPinned holds the default value on creation for the is_pinned field.
	post.DefaultIsPinned = postDescIsPinned.Default.(bool)
	// postDescID is the schema descriptor for id field.
	postDescID := postFields[0].Descriptor()
	// post.IDValidator is a validator for the "id" field. It is called by the builders before save.
	post.IDValidator = postDescID.Validators[0].(func(int) error)
	postactionMixin := schema.PostAction{}.Mixin()
	postactionMixinFields0 := postactionMixin[0].Fields()
	_ = postactionMixinFields0
	postactionFields := schema.PostAction{}.Fields()
	_ = postactionFields
	// postactionDescCreatedAt is the schema descriptor for created_at field.
	postactionDescCreatedAt := postactionMixinFields0[0].Descriptor()
	// postaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	postaction.DefaultCreatedAt = postactionDescCreatedAt.Default.(func() time.Time)
	// postactionDescUpdatedAt is the schema descriptor for updated_at field.
	postactionDescUpdatedAt := postactionMixinFields0[1].Descriptor()
	// postaction.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	postaction.DefaultUpdatedAt = postactionDescUpdatedAt.Default.(func() time.Time)
	// postaction.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	postaction.UpdateDefaultUpdatedAt = postactionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// postactionDescUserID is the schema descriptor for user_id field.
	postactionDescUserID := postactionFields[1].Descriptor()
	// postaction.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	postaction.UserIDValidator = postactionDescUserID.Validators[0].(func(int) error)
	// postactionDescPostID is the schema descriptor for post_id field.
	postactionDescPostID := postactionFields[2].Descriptor()
	// postaction.PostIDValidator is a validator for the "post_id" field. It is called by the builders before save.
	postaction.PostIDValidator = postactionDescPostID.Validators[0].(func(int) error)
	// postactionDescID is the schema descriptor for id field.
	postactionDescID := postactionFields[0].Descriptor()
	// postaction.IDValidator is a validator for the "id" field. It is called by the builders before save.
	postaction.IDValidator = postactionDescID.Validators[0].(func(int) error)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescPasswordSalt is the schema descriptor for password_salt field.
	userDescPasswordSalt := userFields[3].Descriptor()
	// user.PasswordSaltValidator is a validator for the "password_salt" field. It is called by the builders before save.
	user.PasswordSaltValidator = userDescPasswordSalt.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[4].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[8].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	// userDescPoints is the schema descriptor for points field.
	userDescPoints := userFields[9].Descriptor()
	// user.DefaultPoints holds the default value on creation for the points field.
	user.DefaultPoints = userDescPoints.Default.(int)
	// user.PointsValidator is a validator for the "points" field. It is called by the builders before save.
	user.PointsValidator = userDescPoints.Validators[0].(func(int) error)
	// userDescCurrency is the schema descriptor for currency field.
	userDescCurrency := userFields[10].Descriptor()
	// user.DefaultCurrency holds the default value on creation for the currency field.
	user.DefaultCurrency = userDescCurrency.Default.(int)
	// user.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	user.CurrencyValidator = userDescCurrency.Validators[0].(func(int) error)
	// userDescPostCount is the schema descriptor for post_count field.
	userDescPostCount := userFields[11].Descriptor()
	// user.DefaultPostCount holds the default value on creation for the post_count field.
	user.DefaultPostCount = userDescPostCount.Default.(int)
	// user.PostCountValidator is a validator for the "post_count" field. It is called by the builders before save.
	user.PostCountValidator = userDescPostCount.Validators[0].(func(int) error)
	// userDescCommentCount is the schema descriptor for comment_count field.
	userDescCommentCount := userFields[12].Descriptor()
	// user.DefaultCommentCount holds the default value on creation for the comment_count field.
	user.DefaultCommentCount = userDescCommentCount.Default.(int)
	// user.CommentCountValidator is a validator for the "comment_count" field. It is called by the builders before save.
	user.CommentCountValidator = userDescCommentCount.Validators[0].(func(int) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(int) error)
	userloginlogMixin := schema.UserLoginLog{}.Mixin()
	userloginlogMixinFields0 := userloginlogMixin[0].Fields()
	_ = userloginlogMixinFields0
	userloginlogFields := schema.UserLoginLog{}.Fields()
	_ = userloginlogFields
	// userloginlogDescCreatedAt is the schema descriptor for created_at field.
	userloginlogDescCreatedAt := userloginlogMixinFields0[0].Descriptor()
	// userloginlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	userloginlog.DefaultCreatedAt = userloginlogDescCreatedAt.Default.(func() time.Time)
	// userloginlogDescUpdatedAt is the schema descriptor for updated_at field.
	userloginlogDescUpdatedAt := userloginlogMixinFields0[1].Descriptor()
	// userloginlog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userloginlog.DefaultUpdatedAt = userloginlogDescUpdatedAt.Default.(func() time.Time)
	// userloginlog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userloginlog.UpdateDefaultUpdatedAt = userloginlogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userloginlogDescUserID is the schema descriptor for user_id field.
	userloginlogDescUserID := userloginlogFields[1].Descriptor()
	// userloginlog.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	userloginlog.UserIDValidator = userloginlogDescUserID.Validators[0].(func(int) error)
	// userloginlogDescIPAddress is the schema descriptor for ip_address field.
	userloginlogDescIPAddress := userloginlogFields[2].Descriptor()
	// userloginlog.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	userloginlog.IPAddressValidator = userloginlogDescIPAddress.Validators[0].(func(string) error)
	// userloginlogDescSuccess is the schema descriptor for success field.
	userloginlogDescSuccess := userloginlogFields[5].Descriptor()
	// userloginlog.DefaultSuccess holds the default value on creation for the success field.
	userloginlog.DefaultSuccess = userloginlogDescSuccess.Default.(bool)
	// userloginlogDescID is the schema descriptor for id field.
	userloginlogDescID := userloginlogFields[0].Descriptor()
	// userloginlog.IDValidator is a validator for the "id" field. It is called by the builders before save.
	userloginlog.IDValidator = userloginlogDescID.Validators[0].(func(int) error)
}
