// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PokeForum/PokeForum/ent/usersigninstatus"
)

// UserSigninStatusCreate is the builder for creating a UserSigninStatus entity.
type UserSigninStatusCreate struct {
	config
	mutation *UserSigninStatusMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserSigninStatusCreate) SetCreatedAt(v time.Time) *UserSigninStatusCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserSigninStatusCreate) SetNillableCreatedAt(v *time.Time) *UserSigninStatusCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserSigninStatusCreate) SetUpdatedAt(v time.Time) *UserSigninStatusCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserSigninStatusCreate) SetNillableUpdatedAt(v *time.Time) *UserSigninStatusCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserSigninStatusCreate) SetUserID(v int64) *UserSigninStatusCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetLastSigninDate sets the "last_signin_date" field.
func (_c *UserSigninStatusCreate) SetLastSigninDate(v time.Time) *UserSigninStatusCreate {
	_c.mutation.SetLastSigninDate(v)
	return _c
}

// SetContinuousDays sets the "continuous_days" field.
func (_c *UserSigninStatusCreate) SetContinuousDays(v int) *UserSigninStatusCreate {
	_c.mutation.SetContinuousDays(v)
	return _c
}

// SetNillableContinuousDays sets the "continuous_days" field if the given value is not nil.
func (_c *UserSigninStatusCreate) SetNillableContinuousDays(v *int) *UserSigninStatusCreate {
	if v != nil {
		_c.SetContinuousDays(*v)
	}
	return _c
}

// SetTotalDays sets the "total_days" field.
func (_c *UserSigninStatusCreate) SetTotalDays(v int) *UserSigninStatusCreate {
	_c.mutation.SetTotalDays(v)
	return _c
}

// SetNillableTotalDays sets the "total_days" field if the given value is not nil.
func (_c *UserSigninStatusCreate) SetNillableTotalDays(v *int) *UserSigninStatusCreate {
	if v != nil {
		_c.SetTotalDays(*v)
	}
	return _c
}

// Mutation returns the UserSigninStatusMutation object of the builder.
func (_c *UserSigninStatusCreate) Mutation() *UserSigninStatusMutation {
	return _c.mutation
}

// Save creates the UserSigninStatus in the database.
func (_c *UserSigninStatusCreate) Save(ctx context.Context) (*UserSigninStatus, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserSigninStatusCreate) SaveX(ctx context.Context) *UserSigninStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSigninStatusCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSigninStatusCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserSigninStatusCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usersigninstatus.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usersigninstatus.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ContinuousDays(); !ok {
		v := usersigninstatus.DefaultContinuousDays
		_c.mutation.SetContinuousDays(v)
	}
	if _, ok := _c.mutation.TotalDays(); !ok {
		v := usersigninstatus.DefaultTotalDays
		_c.mutation.SetTotalDays(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserSigninStatusCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserSigninStatus.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserSigninStatus.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserSigninStatus.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := usersigninstatus.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserSigninStatus.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastSigninDate(); !ok {
		return &ValidationError{Name: "last_signin_date", err: errors.New(`ent: missing required field "UserSigninStatus.last_signin_date"`)}
	}
	if _, ok := _c.mutation.ContinuousDays(); !ok {
		return &ValidationError{Name: "continuous_days", err: errors.New(`ent: missing required field "UserSigninStatus.continuous_days"`)}
	}
	if v, ok := _c.mutation.ContinuousDays(); ok {
		if err := usersigninstatus.ContinuousDaysValidator(v); err != nil {
			return &ValidationError{Name: "continuous_days", err: fmt.Errorf(`ent: validator failed for field "UserSigninStatus.continuous_days": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalDays(); !ok {
		return &ValidationError{Name: "total_days", err: errors.New(`ent: missing required field "UserSigninStatus.total_days"`)}
	}
	if v, ok := _c.mutation.TotalDays(); ok {
		if err := usersigninstatus.TotalDaysValidator(v); err != nil {
			return &ValidationError{Name: "total_days", err: fmt.Errorf(`ent: validator failed for field "UserSigninStatus.total_days": %w`, err)}
		}
	}
	return nil
}

func (_c *UserSigninStatusCreate) sqlSave(ctx context.Context) (*UserSigninStatus, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserSigninStatusCreate) createSpec() (*UserSigninStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &UserSigninStatus{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usersigninstatus.Table, sqlgraph.NewFieldSpec(usersigninstatus.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usersigninstatus.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usersigninstatus.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(usersigninstatus.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.LastSigninDate(); ok {
		_spec.SetField(usersigninstatus.FieldLastSigninDate, field.TypeTime, value)
		_node.LastSigninDate = value
	}
	if value, ok := _c.mutation.ContinuousDays(); ok {
		_spec.SetField(usersigninstatus.FieldContinuousDays, field.TypeInt, value)
		_node.ContinuousDays = value
	}
	if value, ok := _c.mutation.TotalDays(); ok {
		_spec.SetField(usersigninstatus.FieldTotalDays, field.TypeInt, value)
		_node.TotalDays = value
	}
	return _node, _spec
}

// UserSigninStatusCreateBulk is the builder for creating many UserSigninStatus entities in bulk.
type UserSigninStatusCreateBulk struct {
	config
	err      error
	builders []*UserSigninStatusCreate
}

// Save creates the UserSigninStatus entities in the database.
func (_c *UserSigninStatusCreateBulk) Save(ctx context.Context) ([]*UserSigninStatus, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserSigninStatus, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserSigninStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserSigninStatusCreateBulk) SaveX(ctx context.Context) []*UserSigninStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSigninStatusCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSigninStatusCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
