// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PokeForum/PokeForum/ent/useroauth"
)

// UserOAuthCreate is the builder for creating a UserOAuth entity.
type UserOAuthCreate struct {
	config
	mutation *UserOAuthMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserOAuthCreate) SetCreatedAt(v time.Time) *UserOAuthCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserOAuthCreate) SetNillableCreatedAt(v *time.Time) *UserOAuthCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserOAuthCreate) SetUpdatedAt(v time.Time) *UserOAuthCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserOAuthCreate) SetNillableUpdatedAt(v *time.Time) *UserOAuthCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserOAuthCreate) SetUserID(v int) *UserOAuthCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *UserOAuthCreate) SetProvider(v useroauth.Provider) *UserOAuthCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetProviderUserID sets the "provider_user_id" field.
func (_c *UserOAuthCreate) SetProviderUserID(v string) *UserOAuthCreate {
	_c.mutation.SetProviderUserID(v)
	return _c
}

// SetProviderUsername sets the "provider_username" field.
func (_c *UserOAuthCreate) SetProviderUsername(v string) *UserOAuthCreate {
	_c.mutation.SetProviderUsername(v)
	return _c
}

// SetNillableProviderUsername sets the "provider_username" field if the given value is not nil.
func (_c *UserOAuthCreate) SetNillableProviderUsername(v *string) *UserOAuthCreate {
	if v != nil {
		_c.SetProviderUsername(*v)
	}
	return _c
}

// SetProviderEmail sets the "provider_email" field.
func (_c *UserOAuthCreate) SetProviderEmail(v string) *UserOAuthCreate {
	_c.mutation.SetProviderEmail(v)
	return _c
}

// SetNillableProviderEmail sets the "provider_email" field if the given value is not nil.
func (_c *UserOAuthCreate) SetNillableProviderEmail(v *string) *UserOAuthCreate {
	if v != nil {
		_c.SetProviderEmail(*v)
	}
	return _c
}

// SetProviderAvatar sets the "provider_avatar" field.
func (_c *UserOAuthCreate) SetProviderAvatar(v string) *UserOAuthCreate {
	_c.mutation.SetProviderAvatar(v)
	return _c
}

// SetNillableProviderAvatar sets the "provider_avatar" field if the given value is not nil.
func (_c *UserOAuthCreate) SetNillableProviderAvatar(v *string) *UserOAuthCreate {
	if v != nil {
		_c.SetProviderAvatar(*v)
	}
	return _c
}

// SetExtraData sets the "extra_data" field.
func (_c *UserOAuthCreate) SetExtraData(v map[string]interface{}) *UserOAuthCreate {
	_c.mutation.SetExtraData(v)
	return _c
}

// Mutation returns the UserOAuthMutation object of the builder.
func (_c *UserOAuthCreate) Mutation() *UserOAuthMutation {
	return _c.mutation
}

// Save creates the UserOAuth in the database.
func (_c *UserOAuthCreate) Save(ctx context.Context) (*UserOAuth, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserOAuthCreate) SaveX(ctx context.Context) *UserOAuth {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserOAuthCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserOAuthCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserOAuthCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := useroauth.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := useroauth.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserOAuthCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserOAuth.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserOAuth.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserOAuth.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := useroauth.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserOAuth.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "UserOAuth.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := useroauth.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserOAuth.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderUserID(); !ok {
		return &ValidationError{Name: "provider_user_id", err: errors.New(`ent: missing required field "UserOAuth.provider_user_id"`)}
	}
	if v, ok := _c.mutation.ProviderUserID(); ok {
		if err := useroauth.ProviderUserIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_user_id", err: fmt.Errorf(`ent: validator failed for field "UserOAuth.provider_user_id": %w`, err)}
		}
	}
	return nil
}

func (_c *UserOAuthCreate) sqlSave(ctx context.Context) (*UserOAuth, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserOAuthCreate) createSpec() (*UserOAuth, *sqlgraph.CreateSpec) {
	var (
		_node = &UserOAuth{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(useroauth.Table, sqlgraph.NewFieldSpec(useroauth.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(useroauth.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(useroauth.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(useroauth.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(useroauth.FieldProvider, field.TypeEnum, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ProviderUserID(); ok {
		_spec.SetField(useroauth.FieldProviderUserID, field.TypeString, value)
		_node.ProviderUserID = value
	}
	if value, ok := _c.mutation.ProviderUsername(); ok {
		_spec.SetField(useroauth.FieldProviderUsername, field.TypeString, value)
		_node.ProviderUsername = value
	}
	if value, ok := _c.mutation.ProviderEmail(); ok {
		_spec.SetField(useroauth.FieldProviderEmail, field.TypeString, value)
		_node.ProviderEmail = value
	}
	if value, ok := _c.mutation.ProviderAvatar(); ok {
		_spec.SetField(useroauth.FieldProviderAvatar, field.TypeString, value)
		_node.ProviderAvatar = value
	}
	if value, ok := _c.mutation.ExtraData(); ok {
		_spec.SetField(useroauth.FieldExtraData, field.TypeJSON, value)
		_node.ExtraData = value
	}
	return _node, _spec
}

// UserOAuthCreateBulk is the builder for creating many UserOAuth entities in bulk.
type UserOAuthCreateBulk struct {
	config
	err      error
	builders []*UserOAuthCreate
}

// Save creates the UserOAuth entities in the database.
func (_c *UserOAuthCreateBulk) Save(ctx context.Context) ([]*UserOAuth, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserOAuth, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserOAuthMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserOAuthCreateBulk) SaveX(ctx context.Context) []*UserOAuth {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserOAuthCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserOAuthCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
