// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PokeForum/PokeForum/ent/user"
	"github.com/PokeForum/PokeForum/ent/userloginlog"
)

// UserLoginLogCreate is the builder for creating a UserLoginLog entity.
type UserLoginLogCreate struct {
	config
	mutation *UserLoginLogMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserLoginLogCreate) SetCreatedAt(v time.Time) *UserLoginLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserLoginLogCreate) SetNillableCreatedAt(v *time.Time) *UserLoginLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserLoginLogCreate) SetUpdatedAt(v time.Time) *UserLoginLogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserLoginLogCreate) SetNillableUpdatedAt(v *time.Time) *UserLoginLogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserLoginLogCreate) SetUserID(v int) *UserLoginLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *UserLoginLogCreate) SetIPAddress(v string) *UserLoginLogCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetIPCountry sets the "ip_country" field.
func (_c *UserLoginLogCreate) SetIPCountry(v string) *UserLoginLogCreate {
	_c.mutation.SetIPCountry(v)
	return _c
}

// SetNillableIPCountry sets the "ip_country" field if the given value is not nil.
func (_c *UserLoginLogCreate) SetNillableIPCountry(v *string) *UserLoginLogCreate {
	if v != nil {
		_c.SetIPCountry(*v)
	}
	return _c
}

// SetIPCity sets the "ip_city" field.
func (_c *UserLoginLogCreate) SetIPCity(v string) *UserLoginLogCreate {
	_c.mutation.SetIPCity(v)
	return _c
}

// SetNillableIPCity sets the "ip_city" field if the given value is not nil.
func (_c *UserLoginLogCreate) SetNillableIPCity(v *string) *UserLoginLogCreate {
	if v != nil {
		_c.SetIPCity(*v)
	}
	return _c
}

// SetSuccess sets the "success" field.
func (_c *UserLoginLogCreate) SetSuccess(v bool) *UserLoginLogCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_c *UserLoginLogCreate) SetNillableSuccess(v *bool) *UserLoginLogCreate {
	if v != nil {
		_c.SetSuccess(*v)
	}
	return _c
}

// SetDeviceInfo sets the "device_info" field.
func (_c *UserLoginLogCreate) SetDeviceInfo(v string) *UserLoginLogCreate {
	_c.mutation.SetDeviceInfo(v)
	return _c
}

// SetNillableDeviceInfo sets the "device_info" field if the given value is not nil.
func (_c *UserLoginLogCreate) SetNillableDeviceInfo(v *string) *UserLoginLogCreate {
	if v != nil {
		_c.SetDeviceInfo(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserLoginLogCreate) SetID(v int) *UserLoginLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserLoginLogCreate) SetUser(v *User) *UserLoginLogCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserLoginLogMutation object of the builder.
func (_c *UserLoginLogCreate) Mutation() *UserLoginLogMutation {
	return _c.mutation
}

// Save creates the UserLoginLog in the database.
func (_c *UserLoginLogCreate) Save(ctx context.Context) (*UserLoginLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserLoginLogCreate) SaveX(ctx context.Context) *UserLoginLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserLoginLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserLoginLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserLoginLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userloginlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userloginlog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Success(); !ok {
		v := userloginlog.DefaultSuccess
		_c.mutation.SetSuccess(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserLoginLogCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserLoginLog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserLoginLog.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserLoginLog.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := userloginlog.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserLoginLog.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IPAddress(); !ok {
		return &ValidationError{Name: "ip_address", err: errors.New(`ent: missing required field "UserLoginLog.ip_address"`)}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := userloginlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "UserLoginLog.ip_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "UserLoginLog.success"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := userloginlog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "UserLoginLog.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserLoginLog.user"`)}
	}
	return nil
}

func (_c *UserLoginLogCreate) sqlSave(ctx context.Context) (*UserLoginLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserLoginLogCreate) createSpec() (*UserLoginLog, *sqlgraph.CreateSpec) {
	var (
		_node = &UserLoginLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userloginlog.Table, sqlgraph.NewFieldSpec(userloginlog.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userloginlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userloginlog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(userloginlog.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := _c.mutation.IPCountry(); ok {
		_spec.SetField(userloginlog.FieldIPCountry, field.TypeString, value)
		_node.IPCountry = value
	}
	if value, ok := _c.mutation.IPCity(); ok {
		_spec.SetField(userloginlog.FieldIPCity, field.TypeString, value)
		_node.IPCity = value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(userloginlog.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	if value, ok := _c.mutation.DeviceInfo(); ok {
		_spec.SetField(userloginlog.FieldDeviceInfo, field.TypeString, value)
		_node.DeviceInfo = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userloginlog.UserTable,
			Columns: []string{userloginlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserLoginLogCreateBulk is the builder for creating many UserLoginLog entities in bulk.
type UserLoginLogCreateBulk struct {
	config
	err      error
	builders []*UserLoginLogCreate
}

// Save creates the UserLoginLog entities in the database.
func (_c *UserLoginLogCreateBulk) Save(ctx context.Context) ([]*UserLoginLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserLoginLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserLoginLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserLoginLogCreateBulk) SaveX(ctx context.Context) []*UserLoginLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserLoginLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserLoginLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
