// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PokeForum/PokeForum/ent/user"
	"github.com/PokeForum/PokeForum/ent/userloginlog"
)

// UserLoginLog is the model entity for the UserLoginLog schema.
type UserLoginLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// IPAddress holds the value of the "ip_address" field.
	IPAddress string `json:"ip_address,omitempty"`
	// IPCountry holds the value of the "ip_country" field.
	IPCountry string `json:"ip_country,omitempty"`
	// IPCity holds the value of the "ip_city" field.
	IPCity string `json:"ip_city,omitempty"`
	// Success holds the value of the "success" field.
	Success bool `json:"success,omitempty"`
	// DeviceInfo holds the value of the "device_info" field.
	DeviceInfo string `json:"device_info,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserLoginLogQuery when eager-loading is set.
	Edges        UserLoginLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserLoginLogEdges holds the relations/edges for other nodes in the graph.
type UserLoginLogEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserLoginLogEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserLoginLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userloginlog.FieldSuccess:
			values[i] = new(sql.NullBool)
		case userloginlog.FieldID, userloginlog.FieldUserID:
			values[i] = new(sql.NullInt64)
		case userloginlog.FieldIPAddress, userloginlog.FieldIPCountry, userloginlog.FieldIPCity, userloginlog.FieldDeviceInfo:
			values[i] = new(sql.NullString)
		case userloginlog.FieldCreatedAt, userloginlog.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserLoginLog fields.
func (_m *UserLoginLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userloginlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userloginlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userloginlog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case userloginlog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case userloginlog.FieldIPAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_address", values[i])
			} else if value.Valid {
				_m.IPAddress = value.String
			}
		case userloginlog.FieldIPCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_country", values[i])
			} else if value.Valid {
				_m.IPCountry = value.String
			}
		case userloginlog.FieldIPCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_city", values[i])
			} else if value.Valid {
				_m.IPCity = value.String
			}
		case userloginlog.FieldSuccess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field success", values[i])
			} else if value.Valid {
				_m.Success = value.Bool
			}
		case userloginlog.FieldDeviceInfo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_info", values[i])
			} else if value.Valid {
				_m.DeviceInfo = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserLoginLog.
// This includes values selected through modifiers, order, etc.
func (_m *UserLoginLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserLoginLog entity.
func (_m *UserLoginLog) QueryUser() *UserQuery {
	return NewUserLoginLogClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserLoginLog.
// Note that you need to call UserLoginLog.Unwrap() before calling this method if this UserLoginLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserLoginLog) Update() *UserLoginLogUpdateOne {
	return NewUserLoginLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserLoginLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserLoginLog) Unwrap() *UserLoginLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserLoginLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserLoginLog) String() string {
	var builder strings.Builder
	builder.WriteString("UserLoginLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("ip_address=")
	builder.WriteString(_m.IPAddress)
	builder.WriteString(", ")
	builder.WriteString("ip_country=")
	builder.WriteString(_m.IPCountry)
	builder.WriteString(", ")
	builder.WriteString("ip_city=")
	builder.WriteString(_m.IPCity)
	builder.WriteString(", ")
	builder.WriteString("success=")
	builder.WriteString(fmt.Sprintf("%v", _m.Success))
	builder.WriteString(", ")
	builder.WriteString("device_info=")
	builder.WriteString(_m.DeviceInfo)
	builder.WriteByte(')')
	return builder.String()
}

// UserLoginLogs is a parsable slice of UserLoginLog.
type UserLoginLogs []*UserLoginLog
