// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PokeForum/PokeForum/ent/predicate"
	"github.com/PokeForum/PokeForum/ent/userloginlog"
)

// UserLoginLogUpdate is the builder for updating UserLoginLog entities.
type UserLoginLogUpdate struct {
	config
	hooks    []Hook
	mutation *UserLoginLogMutation
}

// Where appends a list predicates to the UserLoginLogUpdate builder.
func (_u *UserLoginLogUpdate) Where(ps ...predicate.UserLoginLog) *UserLoginLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserLoginLogUpdate) SetUpdatedAt(v time.Time) *UserLoginLogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserLoginLogUpdate) SetUserID(v int) *UserLoginLogUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserLoginLogUpdate) SetNillableUserID(v *int) *UserLoginLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserLoginLogUpdate) AddUserID(v int) *UserLoginLogUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *UserLoginLogUpdate) SetIPAddress(v string) *UserLoginLogUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *UserLoginLogUpdate) SetNillableIPAddress(v *string) *UserLoginLogUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetIPCountry sets the "ip_country" field.
func (_u *UserLoginLogUpdate) SetIPCountry(v string) *UserLoginLogUpdate {
	_u.mutation.SetIPCountry(v)
	return _u
}

// SetNillableIPCountry sets the "ip_country" field if the given value is not nil.
func (_u *UserLoginLogUpdate) SetNillableIPCountry(v *string) *UserLoginLogUpdate {
	if v != nil {
		_u.SetIPCountry(*v)
	}
	return _u
}

// ClearIPCountry clears the value of the "ip_country" field.
func (_u *UserLoginLogUpdate) ClearIPCountry() *UserLoginLogUpdate {
	_u.mutation.ClearIPCountry()
	return _u
}

// SetIPCity sets the "ip_city" field.
func (_u *UserLoginLogUpdate) SetIPCity(v string) *UserLoginLogUpdate {
	_u.mutation.SetIPCity(v)
	return _u
}

// SetNillableIPCity sets the "ip_city" field if the given value is not nil.
func (_u *UserLoginLogUpdate) SetNillableIPCity(v *string) *UserLoginLogUpdate {
	if v != nil {
		_u.SetIPCity(*v)
	}
	return _u
}

// ClearIPCity clears the value of the "ip_city" field.
func (_u *UserLoginLogUpdate) ClearIPCity() *UserLoginLogUpdate {
	_u.mutation.ClearIPCity()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *UserLoginLogUpdate) SetSuccess(v bool) *UserLoginLogUpdate {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *UserLoginLogUpdate) SetNillableSuccess(v *bool) *UserLoginLogUpdate {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetDeviceInfo sets the "device_info" field.
func (_u *UserLoginLogUpdate) SetDeviceInfo(v string) *UserLoginLogUpdate {
	_u.mutation.SetDeviceInfo(v)
	return _u
}

// SetNillableDeviceInfo sets the "device_info" field if the given value is not nil.
func (_u *UserLoginLogUpdate) SetNillableDeviceInfo(v *string) *UserLoginLogUpdate {
	if v != nil {
		_u.SetDeviceInfo(*v)
	}
	return _u
}

// ClearDeviceInfo clears the value of the "device_info" field.
func (_u *UserLoginLogUpdate) ClearDeviceInfo() *UserLoginLogUpdate {
	_u.mutation.ClearDeviceInfo()
	return _u
}

// Mutation returns the UserLoginLogMutation object of the builder.
func (_u *UserLoginLogUpdate) Mutation() *UserLoginLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserLoginLogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserLoginLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserLoginLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserLoginLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserLoginLogUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userloginlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserLoginLogUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := userloginlog.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserLoginLog.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := userloginlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "UserLoginLog.ip_address": %w`, err)}
		}
	}
	return nil
}

func (_u *UserLoginLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userloginlog.Table, userloginlog.Columns, sqlgraph.NewFieldSpec(userloginlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userloginlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userloginlog.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userloginlog.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(userloginlog.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPCountry(); ok {
		_spec.SetField(userloginlog.FieldIPCountry, field.TypeString, value)
	}
	if _u.mutation.IPCountryCleared() {
		_spec.ClearField(userloginlog.FieldIPCountry, field.TypeString)
	}
	if value, ok := _u.mutation.IPCity(); ok {
		_spec.SetField(userloginlog.FieldIPCity, field.TypeString, value)
	}
	if _u.mutation.IPCityCleared() {
		_spec.ClearField(userloginlog.FieldIPCity, field.TypeString)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(userloginlog.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeviceInfo(); ok {
		_spec.SetField(userloginlog.FieldDeviceInfo, field.TypeString, value)
	}
	if _u.mutation.DeviceInfoCleared() {
		_spec.ClearField(userloginlog.FieldDeviceInfo, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userloginlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserLoginLogUpdateOne is the builder for updating a single UserLoginLog entity.
type UserLoginLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserLoginLogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserLoginLogUpdateOne) SetUpdatedAt(v time.Time) *UserLoginLogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserLoginLogUpdateOne) SetUserID(v int) *UserLoginLogUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserLoginLogUpdateOne) SetNillableUserID(v *int) *UserLoginLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserLoginLogUpdateOne) AddUserID(v int) *UserLoginLogUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *UserLoginLogUpdateOne) SetIPAddress(v string) *UserLoginLogUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *UserLoginLogUpdateOne) SetNillableIPAddress(v *string) *UserLoginLogUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetIPCountry sets the "ip_country" field.
func (_u *UserLoginLogUpdateOne) SetIPCountry(v string) *UserLoginLogUpdateOne {
	_u.mutation.SetIPCountry(v)
	return _u
}

// SetNillableIPCountry sets the "ip_country" field if the given value is not nil.
func (_u *UserLoginLogUpdateOne) SetNillableIPCountry(v *string) *UserLoginLogUpdateOne {
	if v != nil {
		_u.SetIPCountry(*v)
	}
	return _u
}

// ClearIPCountry clears the value of the "ip_country" field.
func (_u *UserLoginLogUpdateOne) ClearIPCountry() *UserLoginLogUpdateOne {
	_u.mutation.ClearIPCountry()
	return _u
}

// SetIPCity sets the "ip_city" field.
func (_u *UserLoginLogUpdateOne) SetIPCity(v string) *UserLoginLogUpdateOne {
	_u.mutation.SetIPCity(v)
	return _u
}

// SetNillableIPCity sets the "ip_city" field if the given value is not nil.
func (_u *UserLoginLogUpdateOne) SetNillableIPCity(v *string) *UserLoginLogUpdateOne {
	if v != nil {
		_u.SetIPCity(*v)
	}
	return _u
}

// ClearIPCity clears the value of the "ip_city" field.
func (_u *UserLoginLogUpdateOne) ClearIPCity() *UserLoginLogUpdateOne {
	_u.mutation.ClearIPCity()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *UserLoginLogUpdateOne) SetSuccess(v bool) *UserLoginLogUpdateOne {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *UserLoginLogUpdateOne) SetNillableSuccess(v *bool) *UserLoginLogUpdateOne {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetDeviceInfo sets the "device_info" field.
func (_u *UserLoginLogUpdateOne) SetDeviceInfo(v string) *UserLoginLogUpdateOne {
	_u.mutation.SetDeviceInfo(v)
	return _u
}

// SetNillableDeviceInfo sets the "device_info" field if the given value is not nil.
func (_u *UserLoginLogUpdateOne) SetNillableDeviceInfo(v *string) *UserLoginLogUpdateOne {
	if v != nil {
		_u.SetDeviceInfo(*v)
	}
	return _u
}

// ClearDeviceInfo clears the value of the "device_info" field.
func (_u *UserLoginLogUpdateOne) ClearDeviceInfo() *UserLoginLogUpdateOne {
	_u.mutation.ClearDeviceInfo()
	return _u
}

// Mutation returns the UserLoginLogMutation object of the builder.
func (_u *UserLoginLogUpdateOne) Mutation() *UserLoginLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserLoginLogUpdate builder.
func (_u *UserLoginLogUpdateOne) Where(ps ...predicate.UserLoginLog) *UserLoginLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserLoginLogUpdateOne) Select(field string, fields ...string) *UserLoginLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserLoginLog entity.
func (_u *UserLoginLogUpdateOne) Save(ctx context.Context) (*UserLoginLog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserLoginLogUpdateOne) SaveX(ctx context.Context) *UserLoginLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserLoginLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserLoginLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserLoginLogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userloginlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserLoginLogUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := userloginlog.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserLoginLog.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := userloginlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "UserLoginLog.ip_address": %w`, err)}
		}
	}
	return nil
}

func (_u *UserLoginLogUpdateOne) sqlSave(ctx context.Context) (_node *UserLoginLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userloginlog.Table, userloginlog.Columns, sqlgraph.NewFieldSpec(userloginlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserLoginLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userloginlog.FieldID)
		for _, f := range fields {
			if !userloginlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userloginlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userloginlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userloginlog.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userloginlog.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(userloginlog.FieldIPAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPCountry(); ok {
		_spec.SetField(userloginlog.FieldIPCountry, field.TypeString, value)
	}
	if _u.mutation.IPCountryCleared() {
		_spec.ClearField(userloginlog.FieldIPCountry, field.TypeString)
	}
	if value, ok := _u.mutation.IPCity(); ok {
		_spec.SetField(userloginlog.FieldIPCity, field.TypeString, value)
	}
	if _u.mutation.IPCityCleared() {
		_spec.ClearField(userloginlog.FieldIPCity, field.TypeString)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(userloginlog.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeviceInfo(); ok {
		_spec.SetField(userloginlog.FieldDeviceInfo, field.TypeString, value)
	}
	if _u.mutation.DeviceInfoCleared() {
		_spec.ClearField(userloginlog.FieldDeviceInfo, field.TypeString)
	}
	_node = &UserLoginLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userloginlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
