// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PokeForum/PokeForum/ent/userfollow"
)

// UserFollow is the model entity for the UserFollow schema.
type UserFollow struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 关注者ID | Follower ID
	FollowerID int `json:"follower_id,omitempty"`
	// 被关注者ID | Following ID
	FollowingID  int `json:"following_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserFollow) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userfollow.FieldID, userfollow.FieldFollowerID, userfollow.FieldFollowingID:
			values[i] = new(sql.NullInt64)
		case userfollow.FieldCreatedAt, userfollow.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserFollow fields.
func (_m *UserFollow) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userfollow.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userfollow.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userfollow.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case userfollow.FieldFollowerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field follower_id", values[i])
			} else if value.Valid {
				_m.FollowerID = int(value.Int64)
			}
		case userfollow.FieldFollowingID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field following_id", values[i])
			} else if value.Valid {
				_m.FollowingID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserFollow.
// This includes values selected through modifiers, order, etc.
func (_m *UserFollow) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserFollow.
// Note that you need to call UserFollow.Unwrap() before calling this method if this UserFollow
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserFollow) Update() *UserFollowUpdateOne {
	return NewUserFollowClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserFollow entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserFollow) Unwrap() *UserFollow {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserFollow is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserFollow) String() string {
	var builder strings.Builder
	builder.WriteString("UserFollow(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("follower_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FollowerID))
	builder.WriteString(", ")
	builder.WriteString("following_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FollowingID))
	builder.WriteByte(')')
	return builder.String()
}

// UserFollows is a parsable slice of UserFollow.
type UserFollows []*UserFollow
