// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PokeForum/PokeForum/ent/usersigninlogs"
)

// UserSigninLogsCreate is the builder for creating a UserSigninLogs entity.
type UserSigninLogsCreate struct {
	config
	mutation *UserSigninLogsMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserSigninLogsCreate) SetCreatedAt(v time.Time) *UserSigninLogsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserSigninLogsCreate) SetNillableCreatedAt(v *time.Time) *UserSigninLogsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserSigninLogsCreate) SetUpdatedAt(v time.Time) *UserSigninLogsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserSigninLogsCreate) SetNillableUpdatedAt(v *time.Time) *UserSigninLogsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserSigninLogsCreate) SetUserID(v int64) *UserSigninLogsCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSignDate sets the "sign_date" field.
func (_c *UserSigninLogsCreate) SetSignDate(v time.Time) *UserSigninLogsCreate {
	_c.mutation.SetSignDate(v)
	return _c
}

// Mutation returns the UserSigninLogsMutation object of the builder.
func (_c *UserSigninLogsCreate) Mutation() *UserSigninLogsMutation {
	return _c.mutation
}

// Save creates the UserSigninLogs in the database.
func (_c *UserSigninLogsCreate) Save(ctx context.Context) (*UserSigninLogs, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserSigninLogsCreate) SaveX(ctx context.Context) *UserSigninLogs {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSigninLogsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSigninLogsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserSigninLogsCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usersigninlogs.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usersigninlogs.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserSigninLogsCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserSigninLogs.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserSigninLogs.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserSigninLogs.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := usersigninlogs.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserSigninLogs.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SignDate(); !ok {
		return &ValidationError{Name: "sign_date", err: errors.New(`ent: missing required field "UserSigninLogs.sign_date"`)}
	}
	return nil
}

func (_c *UserSigninLogsCreate) sqlSave(ctx context.Context) (*UserSigninLogs, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserSigninLogsCreate) createSpec() (*UserSigninLogs, *sqlgraph.CreateSpec) {
	var (
		_node = &UserSigninLogs{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usersigninlogs.Table, sqlgraph.NewFieldSpec(usersigninlogs.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usersigninlogs.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usersigninlogs.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(usersigninlogs.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.SignDate(); ok {
		_spec.SetField(usersigninlogs.FieldSignDate, field.TypeTime, value)
		_node.SignDate = value
	}
	return _node, _spec
}

// UserSigninLogsCreateBulk is the builder for creating many UserSigninLogs entities in bulk.
type UserSigninLogsCreateBulk struct {
	config
	err      error
	builders []*UserSigninLogsCreate
}

// Save creates the UserSigninLogs entities in the database.
func (_c *UserSigninLogsCreateBulk) Save(ctx context.Context) ([]*UserSigninLogs, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserSigninLogs, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserSigninLogsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserSigninLogsCreateBulk) SaveX(ctx context.Context) []*UserSigninLogs {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSigninLogsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSigninLogsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
