// Code generated by ent, DO NOT EDIT.

package report

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/PokeForum/PokeForum/ent/predicate"
	"github.com/PokeForum/PokeForum/ent/schema"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldUpdatedAt, v))
}

// ReporterID applies equality check predicate on the "reporter_id" field. It's identical to ReporterIDEQ.
func ReporterID(v int) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldReporterID, v))
}

// TargetID applies equality check predicate on the "target_id" field. It's identical to TargetIDEQ.
func TargetID(v int) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldTargetID, v))
}

// TargetType applies equality check predicate on the "target_type" field. It's identical to TargetTypeEQ.
func TargetType(v schema.ReportTargetType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldEQ(FieldTargetType, vc))
}

// TargetAuthorID applies equality check predicate on the "target_author_id" field. It's identical to TargetAuthorIDEQ.
func TargetAuthorID(v int) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldTargetAuthorID, v))
}

// ReportType applies equality check predicate on the "report_type" field. It's identical to ReportTypeEQ.
func ReportType(v schema.ReportType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldEQ(FieldReportType, vc))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldReason, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v schema.ReportStatus) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldEQ(FieldStatus, vc))
}

// HandlerID applies equality check predicate on the "handler_id" field. It's identical to HandlerIDEQ.
func HandlerID(v int) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldHandlerID, v))
}

// HandleResult applies equality check predicate on the "handle_result" field. It's identical to HandleResultEQ.
func HandleResult(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldHandleResult, v))
}

// HandleAction applies equality check predicate on the "handle_action" field. It's identical to HandleActionEQ.
func HandleAction(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldHandleAction, v))
}

// HandledAt applies equality check predicate on the "handled_at" field. It's identical to HandledAtEQ.
func HandledAt(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldHandledAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldUpdatedAt, v))
}

// ReporterIDEQ applies the EQ predicate on the "reporter_id" field.
func ReporterIDEQ(v int) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldReporterID, v))
}

// ReporterIDNEQ applies the NEQ predicate on the "reporter_id" field.
func ReporterIDNEQ(v int) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldReporterID, v))
}

// ReporterIDIn applies the In predicate on the "reporter_id" field.
func ReporterIDIn(vs ...int) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldReporterID, vs...))
}

// ReporterIDNotIn applies the NotIn predicate on the "reporter_id" field.
func ReporterIDNotIn(vs ...int) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldReporterID, vs...))
}

// ReporterIDGT applies the GT predicate on the "reporter_id" field.
func ReporterIDGT(v int) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldReporterID, v))
}

// ReporterIDGTE applies the GTE predicate on the "reporter_id" field.
func ReporterIDGTE(v int) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldReporterID, v))
}

// ReporterIDLT applies the LT predicate on the "reporter_id" field.
func ReporterIDLT(v int) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldReporterID, v))
}

// ReporterIDLTE applies the LTE predicate on the "reporter_id" field.
func ReporterIDLTE(v int) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldReporterID, v))
}

// TargetIDEQ applies the EQ predicate on the "target_id" field.
func TargetIDEQ(v int) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldTargetID, v))
}

// TargetIDNEQ applies the NEQ predicate on the "target_id" field.
func TargetIDNEQ(v int) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldTargetID, v))
}

// TargetIDIn applies the In predicate on the "target_id" field.
func TargetIDIn(vs ...int) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldTargetID, vs...))
}

// TargetIDNotIn applies the NotIn predicate on the "target_id" field.
func TargetIDNotIn(vs ...int) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldTargetID, vs...))
}

// TargetIDGT applies the GT predicate on the "target_id" field.
func TargetIDGT(v int) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldTargetID, v))
}

// TargetIDGTE applies the GTE predicate on the "target_id" field.
func TargetIDGTE(v int) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldTargetID, v))
}

// TargetIDLT applies the LT predicate on the "target_id" field.
func TargetIDLT(v int) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldTargetID, v))
}

// TargetIDLTE applies the LTE predicate on the "target_id" field.
func TargetIDLTE(v int) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldTargetID, v))
}

// TargetTypeEQ applies the EQ predicate on the "target_type" field.
func TargetTypeEQ(v schema.ReportTargetType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldEQ(FieldTargetType, vc))
}

// TargetTypeNEQ applies the NEQ predicate on the "target_type" field.
func TargetTypeNEQ(v schema.ReportTargetType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldNEQ(FieldTargetType, vc))
}

// TargetTypeIn applies the In predicate on the "target_type" field.
func TargetTypeIn(vs ...schema.ReportTargetType) predicate.Report {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Report(sql.FieldIn(FieldTargetType, v...))
}

// TargetTypeNotIn applies the NotIn predicate on the "target_type" field.
func TargetTypeNotIn(vs ...schema.ReportTargetType) predicate.Report {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Report(sql.FieldNotIn(FieldTargetType, v...))
}

// TargetTypeGT applies the GT predicate on the "target_type" field.
func TargetTypeGT(v schema.ReportTargetType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldGT(FieldTargetType, vc))
}

// TargetTypeGTE applies the GTE predicate on the "target_type" field.
func TargetTypeGTE(v schema.ReportTargetType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldGTE(FieldTargetType, vc))
}

// TargetTypeLT applies the LT predicate on the "target_type" field.
func TargetTypeLT(v schema.ReportTargetType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldLT(FieldTargetType, vc))
}

// TargetTypeLTE applies the LTE predicate on the "target_type" field.
func TargetTypeLTE(v schema.ReportTargetType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldLTE(FieldTargetType, vc))
}

// TargetTypeContains applies the Contains predicate on the "target_type" field.
func TargetTypeContains(v schema.ReportTargetType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldContains(FieldTargetType, vc))
}

// TargetTypeHasPrefix applies the HasPrefix predicate on the "target_type" field.
func TargetTypeHasPrefix(v schema.ReportTargetType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldHasPrefix(FieldTargetType, vc))
}

// TargetTypeHasSuffix applies the HasSuffix predicate on the "target_type" field.
func TargetTypeHasSuffix(v schema.ReportTargetType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldHasSuffix(FieldTargetType, vc))
}

// TargetTypeEqualFold applies the EqualFold predicate on the "target_type" field.
func TargetTypeEqualFold(v schema.ReportTargetType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldEqualFold(FieldTargetType, vc))
}

// TargetTypeContainsFold applies the ContainsFold predicate on the "target_type" field.
func TargetTypeContainsFold(v schema.ReportTargetType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldContainsFold(FieldTargetType, vc))
}

// TargetAuthorIDEQ applies the EQ predicate on the "target_author_id" field.
func TargetAuthorIDEQ(v int) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldTargetAuthorID, v))
}

// TargetAuthorIDNEQ applies the NEQ predicate on the "target_author_id" field.
func TargetAuthorIDNEQ(v int) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldTargetAuthorID, v))
}

// TargetAuthorIDIn applies the In predicate on the "target_author_id" field.
func TargetAuthorIDIn(vs ...int) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldTargetAuthorID, vs...))
}

// TargetAuthorIDNotIn applies the NotIn predicate on the "target_author_id" field.
func TargetAuthorIDNotIn(vs ...int) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldTargetAuthorID, vs...))
}

// TargetAuthorIDGT applies the GT predicate on the "target_author_id" field.
func TargetAuthorIDGT(v int) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldTargetAuthorID, v))
}

// TargetAuthorIDGTE applies the GTE predicate on the "target_author_id" field.
func TargetAuthorIDGTE(v int) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldTargetAuthorID, v))
}

// TargetAuthorIDLT applies the LT predicate on the "target_author_id" field.
func TargetAuthorIDLT(v int) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldTargetAuthorID, v))
}

// TargetAuthorIDLTE applies the LTE predicate on the "target_author_id" field.
func TargetAuthorIDLTE(v int) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldTargetAuthorID, v))
}

// ReportTypeEQ applies the EQ predicate on the "report_type" field.
func ReportTypeEQ(v schema.ReportType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldEQ(FieldReportType, vc))
}

// ReportTypeNEQ applies the NEQ predicate on the "report_type" field.
func ReportTypeNEQ(v schema.ReportType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldNEQ(FieldReportType, vc))
}

// ReportTypeIn applies the In predicate on the "report_type" field.
func ReportTypeIn(vs ...schema.ReportType) predicate.Report {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Report(sql.FieldIn(FieldReportType, v...))
}

// ReportTypeNotIn applies the NotIn predicate on the "report_type" field.
func ReportTypeNotIn(vs ...schema.ReportType) predicate.Report {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Report(sql.FieldNotIn(FieldReportType, v...))
}

// ReportTypeGT applies the GT predicate on the "report_type" field.
func ReportTypeGT(v schema.ReportType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldGT(FieldReportType, vc))
}

// ReportTypeGTE applies the GTE predicate on the "report_type" field.
func ReportTypeGTE(v schema.ReportType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldGTE(FieldReportType, vc))
}

// ReportTypeLT applies the LT predicate on the "report_type" field.
func ReportTypeLT(v schema.ReportType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldLT(FieldReportType, vc))
}

// ReportTypeLTE applies the LTE predicate on the "report_type" field.
func ReportTypeLTE(v schema.ReportType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldLTE(FieldReportType, vc))
}

// ReportTypeContains applies the Contains predicate on the "report_type" field.
func ReportTypeContains(v schema.ReportType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldContains(FieldReportType, vc))
}

// ReportTypeHasPrefix applies the HasPrefix predicate on the "report_type" field.
func ReportTypeHasPrefix(v schema.ReportType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldHasPrefix(FieldReportType, vc))
}

// ReportTypeHasSuffix applies the HasSuffix predicate on the "report_type" field.
func ReportTypeHasSuffix(v schema.ReportType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldHasSuffix(FieldReportType, vc))
}

// ReportTypeEqualFold applies the EqualFold predicate on the "report_type" field.
func ReportTypeEqualFold(v schema.ReportType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldEqualFold(FieldReportType, vc))
}

// ReportTypeContainsFold applies the ContainsFold predicate on the "report_type" field.
func ReportTypeContainsFold(v schema.ReportType) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldContainsFold(FieldReportType, vc))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.Report {
	return predicate.Report(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.Report {
	return predicate.Report(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldReason, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v schema.ReportStatus) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v schema.ReportStatus) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...schema.ReportStatus) predicate.Report {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Report(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...schema.ReportStatus) predicate.Report {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Report(sql.FieldNotIn(FieldStatus, v...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v schema.ReportStatus) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldGT(FieldStatus, vc))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v schema.ReportStatus) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldGTE(FieldStatus, vc))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v schema.ReportStatus) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldLT(FieldStatus, vc))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v schema.ReportStatus) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldLTE(FieldStatus, vc))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v schema.ReportStatus) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldContains(FieldStatus, vc))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v schema.ReportStatus) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldHasPrefix(FieldStatus, vc))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v schema.ReportStatus) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldHasSuffix(FieldStatus, vc))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v schema.ReportStatus) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldEqualFold(FieldStatus, vc))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v schema.ReportStatus) predicate.Report {
	vc := string(v)
	return predicate.Report(sql.FieldContainsFold(FieldStatus, vc))
}

// HandlerIDEQ applies the EQ predicate on the "handler_id" field.
func HandlerIDEQ(v int) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldHandlerID, v))
}

// HandlerIDNEQ applies the NEQ predicate on the "handler_id" field.
func HandlerIDNEQ(v int) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldHandlerID, v))
}

// HandlerIDIn applies the In predicate on the "handler_id" field.
func HandlerIDIn(vs ...int) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldHandlerID, vs...))
}

// HandlerIDNotIn applies the NotIn predicate on the "handler_id" field.
func HandlerIDNotIn(vs ...int) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldHandlerID, vs...))
}

// HandlerIDGT applies the GT predicate on the "handler_id" field.
func HandlerIDGT(v int) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldHandlerID, v))
}

// HandlerIDGTE applies the GTE predicate on the "handler_id" field.
func HandlerIDGTE(v int) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldHandlerID, v))
}

// HandlerIDLT applies the LT predicate on the "handler_id" field.
func HandlerIDLT(v int) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldHandlerID, v))
}

// HandlerIDLTE applies the LTE predicate on the "handler_id" field.
func HandlerIDLTE(v int) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldHandlerID, v))
}

// HandlerIDIsNil applies the IsNil predicate on the "handler_id" field.
func HandlerIDIsNil() predicate.Report {
	return predicate.Report(sql.FieldIsNull(FieldHandlerID))
}

// HandlerIDNotNil applies the NotNil predicate on the "handler_id" field.
func HandlerIDNotNil() predicate.Report {
	return predicate.Report(sql.FieldNotNull(FieldHandlerID))
}

// HandleResultEQ applies the EQ predicate on the "handle_result" field.
func HandleResultEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldHandleResult, v))
}

// HandleResultNEQ applies the NEQ predicate on the "handle_result" field.
func HandleResultNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldHandleResult, v))
}

// HandleResultIn applies the In predicate on the "handle_result" field.
func HandleResultIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldHandleResult, vs...))
}

// HandleResultNotIn applies the NotIn predicate on the "handle_result" field.
func HandleResultNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldHandleResult, vs...))
}

// HandleResultGT applies the GT predicate on the "handle_result" field.
func HandleResultGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldHandleResult, v))
}

// HandleResultGTE applies the GTE predicate on the "handle_result" field.
func HandleResultGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldHandleResult, v))
}

// HandleResultLT applies the LT predicate on the "handle_result" field.
func HandleResultLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldHandleResult, v))
}

// HandleResultLTE applies the LTE predicate on the "handle_result" field.
func HandleResultLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldHandleResult, v))
}

// HandleResultContains applies the Contains predicate on the "handle_result" field.
func HandleResultContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldHandleResult, v))
}

// HandleResultHasPrefix applies the HasPrefix predicate on the "handle_result" field.
func HandleResultHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldHandleResult, v))
}

// HandleResultHasSuffix applies the HasSuffix predicate on the "handle_result" field.
func HandleResultHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldHandleResult, v))
}

// HandleResultIsNil applies the IsNil predicate on the "handle_result" field.
func HandleResultIsNil() predicate.Report {
	return predicate.Report(sql.FieldIsNull(FieldHandleResult))
}

// HandleResultNotNil applies the NotNil predicate on the "handle_result" field.
func HandleResultNotNil() predicate.Report {
	return predicate.Report(sql.FieldNotNull(FieldHandleResult))
}

// HandleResultEqualFold applies the EqualFold predicate on the "handle_result" field.
func HandleResultEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldHandleResult, v))
}

// HandleResultContainsFold applies the ContainsFold predicate on the "handle_result" field.
func HandleResultContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldHandleResult, v))
}

// HandleActionEQ applies the EQ predicate on the "handle_action" field.
func HandleActionEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldHandleAction, v))
}

// HandleActionNEQ applies the NEQ predicate on the "handle_action" field.
func HandleActionNEQ(v string) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldHandleAction, v))
}

// HandleActionIn applies the In predicate on the "handle_action" field.
func HandleActionIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldHandleAction, vs...))
}

// HandleActionNotIn applies the NotIn predicate on the "handle_action" field.
func HandleActionNotIn(vs ...string) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldHandleAction, vs...))
}

// HandleActionGT applies the GT predicate on the "handle_action" field.
func HandleActionGT(v string) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldHandleAction, v))
}

// HandleActionGTE applies the GTE predicate on the "handle_action" field.
func HandleActionGTE(v string) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldHandleAction, v))
}

// HandleActionLT applies the LT predicate on the "handle_action" field.
func HandleActionLT(v string) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldHandleAction, v))
}

// HandleActionLTE applies the LTE predicate on the "handle_action" field.
func HandleActionLTE(v string) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldHandleAction, v))
}

// HandleActionContains applies the Contains predicate on the "handle_action" field.
func HandleActionContains(v string) predicate.Report {
	return predicate.Report(sql.FieldContains(FieldHandleAction, v))
}

// HandleActionHasPrefix applies the HasPrefix predicate on the "handle_action" field.
func HandleActionHasPrefix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasPrefix(FieldHandleAction, v))
}

// HandleActionHasSuffix applies the HasSuffix predicate on the "handle_action" field.
func HandleActionHasSuffix(v string) predicate.Report {
	return predicate.Report(sql.FieldHasSuffix(FieldHandleAction, v))
}

// HandleActionIsNil applies the IsNil predicate on the "handle_action" field.
func HandleActionIsNil() predicate.Report {
	return predicate.Report(sql.FieldIsNull(FieldHandleAction))
}

// HandleActionNotNil applies the NotNil predicate on the "handle_action" field.
func HandleActionNotNil() predicate.Report {
	return predicate.Report(sql.FieldNotNull(FieldHandleAction))
}

// HandleActionEqualFold applies the EqualFold predicate on the "handle_action" field.
func HandleActionEqualFold(v string) predicate.Report {
	return predicate.Report(sql.FieldEqualFold(FieldHandleAction, v))
}

// HandleActionContainsFold applies the ContainsFold predicate on the "handle_action" field.
func HandleActionContainsFold(v string) predicate.Report {
	return predicate.Report(sql.FieldContainsFold(FieldHandleAction, v))
}

// HandledAtEQ applies the EQ predicate on the "handled_at" field.
func HandledAtEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldEQ(FieldHandledAt, v))
}

// HandledAtNEQ applies the NEQ predicate on the "handled_at" field.
func HandledAtNEQ(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldNEQ(FieldHandledAt, v))
}

// HandledAtIn applies the In predicate on the "handled_at" field.
func HandledAtIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldIn(FieldHandledAt, vs...))
}

// HandledAtNotIn applies the NotIn predicate on the "handled_at" field.
func HandledAtNotIn(vs ...time.Time) predicate.Report {
	return predicate.Report(sql.FieldNotIn(FieldHandledAt, vs...))
}

// HandledAtGT applies the GT predicate on the "handled_at" field.
func HandledAtGT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGT(FieldHandledAt, v))
}

// HandledAtGTE applies the GTE predicate on the "handled_at" field.
func HandledAtGTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldGTE(FieldHandledAt, v))
}

// HandledAtLT applies the LT predicate on the "handled_at" field.
func HandledAtLT(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLT(FieldHandledAt, v))
}

// HandledAtLTE applies the LTE predicate on the "handled_at" field.
func HandledAtLTE(v time.Time) predicate.Report {
	return predicate.Report(sql.FieldLTE(FieldHandledAt, v))
}

// HandledAtIsNil applies the IsNil predicate on the "handled_at" field.
func HandledAtIsNil() predicate.Report {
	return predicate.Report(sql.FieldIsNull(FieldHandledAt))
}

// HandledAtNotNil applies the NotNil predicate on the "handled_at" field.
func HandledAtNotNil() predicate.Report {
	return predicate.Report(sql.FieldNotNull(FieldHandledAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Report) predicate.Report {
	return predicate.Report(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Report) predicate.Report {
	return predicate.Report(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Report) predicate.Report {
	return predicate.Report(sql.NotPredicates(p))
}
