// Code generated by ent, DO NOT EDIT.

package userloginlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/PokeForum/PokeForum/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldUserID, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldIPAddress, v))
}

// IPCountry applies equality check predicate on the "ip_country" field. It's identical to IPCountryEQ.
func IPCountry(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldIPCountry, v))
}

// IPCity applies equality check predicate on the "ip_city" field. It's identical to IPCityEQ.
func IPCity(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldIPCity, v))
}

// Success applies equality check predicate on the "success" field. It's identical to SuccessEQ.
func Success(v bool) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldSuccess, v))
}

// DeviceInfo applies equality check predicate on the "device_info" field. It's identical to DeviceInfoEQ.
func DeviceInfo(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldDeviceInfo, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNotIn(FieldUserID, vs...))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldContainsFold(FieldIPAddress, v))
}

// IPCountryEQ applies the EQ predicate on the "ip_country" field.
func IPCountryEQ(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldIPCountry, v))
}

// IPCountryNEQ applies the NEQ predicate on the "ip_country" field.
func IPCountryNEQ(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNEQ(FieldIPCountry, v))
}

// IPCountryIn applies the In predicate on the "ip_country" field.
func IPCountryIn(vs ...string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldIn(FieldIPCountry, vs...))
}

// IPCountryNotIn applies the NotIn predicate on the "ip_country" field.
func IPCountryNotIn(vs ...string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNotIn(FieldIPCountry, vs...))
}

// IPCountryGT applies the GT predicate on the "ip_country" field.
func IPCountryGT(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldGT(FieldIPCountry, v))
}

// IPCountryGTE applies the GTE predicate on the "ip_country" field.
func IPCountryGTE(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldGTE(FieldIPCountry, v))
}

// IPCountryLT applies the LT predicate on the "ip_country" field.
func IPCountryLT(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldLT(FieldIPCountry, v))
}

// IPCountryLTE applies the LTE predicate on the "ip_country" field.
func IPCountryLTE(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldLTE(FieldIPCountry, v))
}

// IPCountryContains applies the Contains predicate on the "ip_country" field.
func IPCountryContains(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldContains(FieldIPCountry, v))
}

// IPCountryHasPrefix applies the HasPrefix predicate on the "ip_country" field.
func IPCountryHasPrefix(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldHasPrefix(FieldIPCountry, v))
}

// IPCountryHasSuffix applies the HasSuffix predicate on the "ip_country" field.
func IPCountryHasSuffix(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldHasSuffix(FieldIPCountry, v))
}

// IPCountryIsNil applies the IsNil predicate on the "ip_country" field.
func IPCountryIsNil() predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldIsNull(FieldIPCountry))
}

// IPCountryNotNil applies the NotNil predicate on the "ip_country" field.
func IPCountryNotNil() predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNotNull(FieldIPCountry))
}

// IPCountryEqualFold applies the EqualFold predicate on the "ip_country" field.
func IPCountryEqualFold(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEqualFold(FieldIPCountry, v))
}

// IPCountryContainsFold applies the ContainsFold predicate on the "ip_country" field.
func IPCountryContainsFold(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldContainsFold(FieldIPCountry, v))
}

// IPCityEQ applies the EQ predicate on the "ip_city" field.
func IPCityEQ(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldIPCity, v))
}

// IPCityNEQ applies the NEQ predicate on the "ip_city" field.
func IPCityNEQ(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNEQ(FieldIPCity, v))
}

// IPCityIn applies the In predicate on the "ip_city" field.
func IPCityIn(vs ...string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldIn(FieldIPCity, vs...))
}

// IPCityNotIn applies the NotIn predicate on the "ip_city" field.
func IPCityNotIn(vs ...string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNotIn(FieldIPCity, vs...))
}

// IPCityGT applies the GT predicate on the "ip_city" field.
func IPCityGT(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldGT(FieldIPCity, v))
}

// IPCityGTE applies the GTE predicate on the "ip_city" field.
func IPCityGTE(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldGTE(FieldIPCity, v))
}

// IPCityLT applies the LT predicate on the "ip_city" field.
func IPCityLT(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldLT(FieldIPCity, v))
}

// IPCityLTE applies the LTE predicate on the "ip_city" field.
func IPCityLTE(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldLTE(FieldIPCity, v))
}

// IPCityContains applies the Contains predicate on the "ip_city" field.
func IPCityContains(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldContains(FieldIPCity, v))
}

// IPCityHasPrefix applies the HasPrefix predicate on the "ip_city" field.
func IPCityHasPrefix(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldHasPrefix(FieldIPCity, v))
}

// IPCityHasSuffix applies the HasSuffix predicate on the "ip_city" field.
func IPCityHasSuffix(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldHasSuffix(FieldIPCity, v))
}

// IPCityIsNil applies the IsNil predicate on the "ip_city" field.
func IPCityIsNil() predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldIsNull(FieldIPCity))
}

// IPCityNotNil applies the NotNil predicate on the "ip_city" field.
func IPCityNotNil() predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNotNull(FieldIPCity))
}

// IPCityEqualFold applies the EqualFold predicate on the "ip_city" field.
func IPCityEqualFold(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEqualFold(FieldIPCity, v))
}

// IPCityContainsFold applies the ContainsFold predicate on the "ip_city" field.
func IPCityContainsFold(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldContainsFold(FieldIPCity, v))
}

// SuccessEQ applies the EQ predicate on the "success" field.
func SuccessEQ(v bool) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldSuccess, v))
}

// SuccessNEQ applies the NEQ predicate on the "success" field.
func SuccessNEQ(v bool) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNEQ(FieldSuccess, v))
}

// DeviceInfoEQ applies the EQ predicate on the "device_info" field.
func DeviceInfoEQ(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEQ(FieldDeviceInfo, v))
}

// DeviceInfoNEQ applies the NEQ predicate on the "device_info" field.
func DeviceInfoNEQ(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNEQ(FieldDeviceInfo, v))
}

// DeviceInfoIn applies the In predicate on the "device_info" field.
func DeviceInfoIn(vs ...string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldIn(FieldDeviceInfo, vs...))
}

// DeviceInfoNotIn applies the NotIn predicate on the "device_info" field.
func DeviceInfoNotIn(vs ...string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNotIn(FieldDeviceInfo, vs...))
}

// DeviceInfoGT applies the GT predicate on the "device_info" field.
func DeviceInfoGT(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldGT(FieldDeviceInfo, v))
}

// DeviceInfoGTE applies the GTE predicate on the "device_info" field.
func DeviceInfoGTE(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldGTE(FieldDeviceInfo, v))
}

// DeviceInfoLT applies the LT predicate on the "device_info" field.
func DeviceInfoLT(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldLT(FieldDeviceInfo, v))
}

// DeviceInfoLTE applies the LTE predicate on the "device_info" field.
func DeviceInfoLTE(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldLTE(FieldDeviceInfo, v))
}

// DeviceInfoContains applies the Contains predicate on the "device_info" field.
func DeviceInfoContains(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldContains(FieldDeviceInfo, v))
}

// DeviceInfoHasPrefix applies the HasPrefix predicate on the "device_info" field.
func DeviceInfoHasPrefix(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldHasPrefix(FieldDeviceInfo, v))
}

// DeviceInfoHasSuffix applies the HasSuffix predicate on the "device_info" field.
func DeviceInfoHasSuffix(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldHasSuffix(FieldDeviceInfo, v))
}

// DeviceInfoIsNil applies the IsNil predicate on the "device_info" field.
func DeviceInfoIsNil() predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldIsNull(FieldDeviceInfo))
}

// DeviceInfoNotNil applies the NotNil predicate on the "device_info" field.
func DeviceInfoNotNil() predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldNotNull(FieldDeviceInfo))
}

// DeviceInfoEqualFold applies the EqualFold predicate on the "device_info" field.
func DeviceInfoEqualFold(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldEqualFold(FieldDeviceInfo, v))
}

// DeviceInfoContainsFold applies the ContainsFold predicate on the "device_info" field.
func DeviceInfoContainsFold(v string) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.FieldContainsFold(FieldDeviceInfo, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserLoginLog {
	return predicate.UserLoginLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserLoginLog {
	return predicate.UserLoginLog(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserLoginLog) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserLoginLog) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserLoginLog) predicate.UserLoginLog {
	return predicate.UserLoginLog(sql.NotPredicates(p))
}
