// Code generated by ent, DO NOT EDIT.

package comment

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the comment type in the database.
	Label = "comment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPostID holds the string denoting the post_id field in the database.
	FieldPostID = "post_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parent_id"
	// FieldReplyToUserID holds the string denoting the reply_to_user_id field in the database.
	FieldReplyToUserID = "reply_to_user_id"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldLikeCount holds the string denoting the like_count field in the database.
	FieldLikeCount = "like_count"
	// FieldDislikeCount holds the string denoting the dislike_count field in the database.
	FieldDislikeCount = "dislike_count"
	// FieldIsSelected holds the string denoting the is_selected field in the database.
	FieldIsSelected = "is_selected"
	// FieldIsPinned holds the string denoting the is_pinned field in the database.
	FieldIsPinned = "is_pinned"
	// FieldCommenterIP holds the string denoting the commenter_ip field in the database.
	FieldCommenterIP = "commenter_ip"
	// FieldDeviceInfo holds the string denoting the device_info field in the database.
	FieldDeviceInfo = "device_info"
	// Table holds the table name of the comment in the database.
	Table = "comments"
)

// Columns holds all SQL columns for comment fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPostID,
	FieldUserID,
	FieldParentID,
	FieldReplyToUserID,
	FieldContent,
	FieldLikeCount,
	FieldDislikeCount,
	FieldIsSelected,
	FieldIsPinned,
	FieldCommenterIP,
	FieldDeviceInfo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PostIDValidator is a validator for the "post_id" field. It is called by the builders before save.
	PostIDValidator func(int) error
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(int) error
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
	// DefaultLikeCount holds the default value on creation for the "like_count" field.
	DefaultLikeCount int
	// LikeCountValidator is a validator for the "like_count" field. It is called by the builders before save.
	LikeCountValidator func(int) error
	// DefaultDislikeCount holds the default value on creation for the "dislike_count" field.
	DefaultDislikeCount int
	// DislikeCountValidator is a validator for the "dislike_count" field. It is called by the builders before save.
	DislikeCountValidator func(int) error
	// DefaultIsSelected holds the default value on creation for the "is_selected" field.
	DefaultIsSelected bool
	// DefaultIsPinned holds the default value on creation for the "is_pinned" field.
	DefaultIsPinned bool
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the Comment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPostID orders the results by the post_id field.
func ByPostID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByParentID orders the results by the parent_id field.
func ByParentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentID, opts...).ToFunc()
}

// ByReplyToUserID orders the results by the reply_to_user_id field.
func ByReplyToUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplyToUserID, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByLikeCount orders the results by the like_count field.
func ByLikeCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLikeCount, opts...).ToFunc()
}

// ByDislikeCount orders the results by the dislike_count field.
func ByDislikeCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDislikeCount, opts...).ToFunc()
}

// ByIsSelected orders the results by the is_selected field.
func ByIsSelected(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSelected, opts...).ToFunc()
}

// ByIsPinned orders the results by the is_pinned field.
func ByIsPinned(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPinned, opts...).ToFunc()
}

// ByCommenterIP orders the results by the commenter_ip field.
func ByCommenterIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommenterIP, opts...).ToFunc()
}

// ByDeviceInfo orders the results by the device_info field.
func ByDeviceInfo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceInfo, opts...).ToFunc()
}
